In [3]:
# # T0100流動資產 = data.get("流動資產合計", 1000)
# # T0960非流動資產 = data.get("非流動資產合計", 1000).fillna(data.get("非流動資產淨額", 1000))
# # T0010資產總額 = T0100流動資產 + T0960非流動資產
# # T1000負債總額 = data.get("負債總額", 1000).fillna(data.get("負債總計", 1000))
# # R505_負債比率 = T1000負債總額 / T0010資產總額 * 100

# # td = R505_負債比率['2330']

# # print(td)
# # print( (td<30) & (td<30).shift(1) & (td<30).shift(2))

from finlab.data import Data
import pandas as pd
from finlab import ml
import talib
import time
import numpy as np

data = Data()
rev = data.get("當月營收")
print(rev['2330'])

date
2005-02-10     20842779.0
2005-03-10     17200047.0
2005-04-10     17610390.0
2005-05-10     18903406.0
2005-06-10     19507661.0
                 ...
2020-12-10    124865438.0
2021-01-10    117364912.0
2021-02-10    126749152.0
2021-03-10    106533690.0
2021-04-10    129127388.0
Name: 2330, Length: 195, dtype: float64

In [2]:
from finlab.data import Data
import pandas as pd
from finlab import ml
import talib
import time
import numpy as np

data = Data()


T3395營業利益 = data.get('營業利益（損失）', 1000).fillna(data.get('營業利益', 1000))
T3100營業收入淨額 = data.get("營業收入合計", 1000)
R106_營業利益率 = T3395營業利益 / T3100營業收入淨額 *100

print(R106_營業利益率['2330'])

date
2013-05-15    33.466167
2013-08-14    36.968659
2013-11-14    36.670649
2014-03-31    32.751922
2014-05-15    35.436561
2014-08-14    38.637161
2014-11-14    40.388468
2015-03-31    39.646595
2015-05-15    39.014776
2015-08-14    37.514190
2015-11-14    36.888053
2016-03-31    38.307891
2016-05-15    34.628462
2016-08-14    41.170851
2016-11-14    40.806344
2017-03-31    41.913013
2017-05-15    40.763796
2017-08-14    38.930733
2017-11-14    38.894715
2018-03-31    39.231505
2018-05-15    39.030742
2018-08-14    36.192258
2018-11-14    36.583813
2019-03-31    36.968347
2019-05-15    29.384870
2019-08-14    31.661633
2019-11-14    36.815892
2020-03-31    39.164315
2020-05-15    41.378880
2020-08-14    42.193507
2020-11-14    42.097732
2021-03-31    43.459421
Name: 2330, dtype: float64

In [1]:
from finlab.data import Data
import pandas as pd
from finlab import ml
import talib
import time
import numpy as np

data = Data()

rev = data.get("當月營收")
rev.index = rev.index.shift(1, "d")  #晚五天才知道營收

revenue_yoy = round(100*((rev/rev.shift(12))-1),2)
revenue_yoy_average3 = revenue_yoy.rolling(3).mean()
revenue_yoy_average12 = revenue_yoy.rolling(12).mean()

T3395營業利益 = data.get('營業利益（損失）', 1000).fillna(data.get('營業利益', 1000))
T3100營業收入淨額 = data.get("營業收入合計", 1000)
R106_營業利益率 = T3395營業利益 / T3100營業收入淨額 *100

T3295營業毛利 = data.get('營業毛利（毛損）', 1000).fillna(data.get('營業毛利（毛損）淨額', 1000))
R105_營業毛利率 = T3295營業毛利 / T3100營業收入淨額 *100

grossratio_yoy = round(100*((R105_營業毛利率/R105_營業毛利率.shift(4))-1),2)
profitratio_yoy = round(100*((R106_營業利益率/R106_營業利益率.shift(4))-1),2)

T0100流動資產 = data.get("流動資產合計", 1000)
T0960非流動資產 = data.get("非流動資產合計", 1000).fillna(data.get("非流動資產淨額", 1000))
T0010資產總額 = T0100流動資產 + T0960非流動資產
T1000負債總額 = data.get("負債總額", 1000).fillna(data.get("負債總計", 1000))
R505_負債比率 = T1000負債總額 / T0010資產總額 * 100

debt_smaller_than_50_oneyear = (R505_負債比率<50) & (R505_負債比率<50).shift(1) & (R505_負債比率<50).shift(2)

T3970經常稅後淨利 = data.get('本期淨利（淨損）',1000).fillna(data.get('本期稅後淨利（淨損）',1000))
T3100營業收入淨額 = data.get("營業收入合計", 1000)
R108_稅後淨利率 = T3970經常稅後淨利 / T3100營業收入淨額 *100

T2000權益總計 = data.get('權益總計', 1000).fillna(data.get('權益總額', 1000))
T3971本期綜合損益總額 = data.get("本期綜合損益總額", 1000).fillna(data.get("綜合損益總額", 1000))
R11U_ROE綜合損益 =  (T3971本期綜合損益總額/((T2000權益總計+T2000權益總計.shift())/2)) * 100

股本 = data.get('股本合計', 1000)
T7210營運現金流 = data.get("營運產生之現金流入（流出）", 1000)
R303_每股現金流量 = T7210營運現金流 / 股本 * 10
R303_每股現金流量_average4 = R303_每股現金流量.rolling(4).mean()

close = data.get("收盤價")
adj_close = data.get_adj('收盤價')

close = close.fillna(method='backfill')
adj_close = adj_close.fillna(method='backfill')

para = 7

recent_rev = (rev.rolling(para).mean()>rev.rolling(para).mean().shift(1))

close_20 = close.rolling(20).mean()
close_60 = close.rolling(60).mean()
close_120 = close.rolling(120).mean()
close_240 = close.rolling(240).mean()

features = {
    'close': close,
    'close_20': close_20,
    'close_60': close_60,
    'close_120': close_120,
    'close_240': close_240,
    'adj_close': adj_close,
    'grossratio_yoy': grossratio_yoy,
    'profitratio_yoy': profitratio_yoy,
    'revenue_yoy': revenue_yoy,
    'revenue_yoy_average3': revenue_yoy_average3,
    'revenue_yoy_average12': revenue_yoy_average12,
    'recent_rev': recent_rev,
    'recent_rev2': recent_rev & recent_rev.shift(1),
    'recent_rev3': recent_rev & recent_rev.shift(1) & recent_rev.shift(2),
    'debt_smaller_than_50_oneyear': debt_smaller_than_50_oneyear,
    'R108_稅後淨利率': R108_稅後淨利率,
    'R11U_ROE綜合損益': R11U_ROE綜合損益,
    'R303_每股現金流量_average4': R303_每股現金流量_average4,
}

trading_frequency = rev.index

for name, f in features.items():
    features[name] = f.reindex(trading_frequency, method='ffill')
    
for name, f in features.items():
    features[name] = f.unstack()
    
dataset = pd.DataFrame(features)
dataset = dataset.reset_index().set_index("date")
# dataset.loc[:,'close':'adj_close'] = dataset.loc[:,'close':'adj_close'].fillna(method='backfill')

In [4]:
# temprevenuestock = rev['3217'].copy()

# para = 7

# aaa = (temprevenuestock.rolling(para).mean()>temprevenuestock.rolling(para).mean().shift(1))

# temp_revenue_df = pd.DataFrame(
#                     {  
#                      'Date':temprevenuestock.index, 
#                      'revenue':temprevenuestock,
# #                      'revenue_recent5':temprevenuestock.rolling(para).mean(),  
# #                      'gg':temprevenuestock.rolling(para).mean().shift(1),   
#                      'test_tf': aaa,
#                      'test2': aaa & aaa.shift(1),
#                      'test3': aaa & aaa.shift(1) & aaa.shift(2),  
# #                      'revenue_shift12':revenuestock.shift(12),
# #                      'YoY':yoy,
# #                      'YoY_average3':yoy.rolling(3).mean(),
# #                      'YoY_average12':yoy.rolling(12).mean(),
# #                      'revenue_status':np.nan,   
# #                      'Date_String': revenuestock.index.astype(str)   
#                      }
#                     )    


# # temprevenuestock['rolling3'] = temprevenuestockrolling(3).mean()
# print(temp_revenue_df)

In [5]:
# print(rev['1262'])
# close['1262'].to_csv('test1262.csv')
# print(close['1235'].loc['2019-09-11'])

In [6]:
# print(dataset[dataset['stock_id']=='1235'])

In [7]:
# # print(dataset[dataset['stock_id'=='2330']])
# print(dataset[dataset['stock_id']=='2330'])

In [8]:
# print(grossratio_yoy['3217'])

In [9]:
# print(tempdf[tempdf['buy_sell_price']!=0])

In [10]:
# # print(tempdf.index == '2020-7-11')
# print( len((tempdf[tempdf['buyprice']!=0])['buyprice']))
# print( (tempdf[tempdf['sellprice']!=0])['sellprice'].values/(tempdf[tempdf['buyprice']!=0])['buyprice'].values)

# print(tempdf[~np.isnan(tempdf['profit']])
             
# print(tempdf[~np.isnan(tempdf['profit'])] )             
             
# print(tempdf['profit'].mean())
# tt = tempdf[tempdf['stock_id']=='2454']
# print(tt[tt['diff']!=0])
# print(tt[~np.isnan(tt['profit'])])
# print(tt)

In [11]:
# datasettest = dataset[ dataset.index >= (profitratio_yoy.index)[0] ]
# datasettest = datasettest[datasettest['stock_id']>='1101']
# print(tempdf['hold'].diff().fillna(0))
# print(tempdf[tempdf['hold'].diff().fillna(0)!=0])
# print( ( ((tempdf[tempdf['hold'].diff().fillna(0)!=0].index.to_series().diff())[1::2])/ np.timedelta64(1, 'D') ).astype(int) )


# ggg = tempdf[tempdf['hold'].diff().fillna(0)!=0].index.to_series().diff()
# print(ggg)
# print(ggg[1::2])
# print( ( (tempdf[tempdf['hold'].diff().fillna(0)!=0].index.to_series().diff())/ np.timedelta64(1, 'D') ).astype(int) )

In [2]:
# print(datasettest['stock_id'].unique())
volume_mean = (data.get("成交股數")/1000).mean()
datasettest = dataset[ dataset.index >= (profitratio_yoy.index)[0] ].copy()
datasettest = datasettest[datasettest['stock_id'].isin(volume_mean[volume_mean>200].index)].copy()
datasettest = datasettest[datasettest['stock_id']>='1101'].copy()
datasettest = datasettest[(datasettest.index<='2021-01-11') & (datasettest.index>='2018-01-11')].copy()

In [21]:
# print(datasettest[datasettest.index<='2020-7-11'].copy())


# print(datasettest.copy())
# print(volume_mean[volume_mean>200].index)

In [14]:
# del tempdf
# print(datasettest.copy())
# tempdf = datasettest.copy()
# print(tempdf)

# code

In [3]:
# tempdf = datasettest[datasettest['stock_id']=='3217']
# tempdf = datasettest[datasettest['stock_id'].isin(['3217', '2454'])]
# tempdf = datasettest[datasettest['stock_id']=='2454']

import time
tStart = time.time()
# stock_id = '1333'

# tempdf = datasettest[datasettest['stock_id']==stock_id].copy()

# print(stock_id)

tempdf = datasettest.copy()

con0 = ~np.isnan(tempdf['close']) & ~np.isnan(tempdf['adj_close'])
con1 = (tempdf.index != '2021-01-11')
con2 = (tempdf['revenue_yoy_average3'] > tempdf['revenue_yoy_average12'])
# con2 = (tempdf['revenue_yoy'] > 0)
con3 = (tempdf['grossratio_yoy']>10)
con4 = (tempdf['profitratio_yoy']>10)
# con5 = (tempdf['close']>30)
con5 = (tempdf['close']>30)
con6 = tempdf['recent_rev']
con7 = tempdf['recent_rev2']
con8 = tempdf['recent_rev3']
con9 = tempdf['debt_smaller_than_50_oneyear']
con10 = tempdf['close_60'] > tempdf['close_120']
con11 = tempdf['close_120'] > tempdf['close_240']
con12 = tempdf['close_20'] > tempdf['close_60']
con13 = tempdf['R108_稅後淨利率']>8
con14 = tempdf['R11U_ROE綜合損益']>3
con15 = tempdf['R303_每股現金流量_average4']>2
con16 = tempdf['R108_稅後淨利率']>3


# holdcon = (con0 & con1 & con2).astype(int)

# holdcon = (con0 & con1 & con2 & con3 &con4 &con5).astype(int)
# holdcon = (con0 & con1 & con2& con3 &con4).astype(int)

# holdcon = (con0 & con1 & con2& con3 &con4& con9 & con15).astype(int) #1.314
# holdcon = (con0 & con1 & con2& con3 &con4& con9 & con15 & con13).astype(int) #1.317
# holdcon = (con0 & con1 & con2& con3 & con4 & con9 & con15 & con13 & con6 ).astype(int) #1.35
# holdcon = (con0 & con1 & con2& con3 & con4 & con9 & con15 & con16 & con6 & con12 & con11).astype(int) #.1418

# holdcon = (con0 & con1 & con2& con3 & con4 & con9 & con15 & con16 & con6 & con12 & con11).astype(int)  #.144136

# holdcon = (con0 & con1 & con2& con3 & con4 & con9 & con15 & con16 & con6 & con12 & con11 & con10).astype(int) #1.42037
holdcon = (con0 & con1 & con2& con3 & con4 & con9 & con15 & con16 & con6 & con12 & con11 & con10 & con14).astype(int) #1.3789


# holdcon = (con0 & con1 & con2 & con4 & con5 & con8 & con9 & con10 & con11 & con13 & con15).astype(int) #(con0 & con1 & con6 & con5).astype(int)

# print(tempdf)
# print(holdcon)

# con0 = ~np.isnan(tempdf['close']) & ~np.isnan(tempdf['close'])
# con1 = (tempdf.index != '2020-7-11')
# con2 = (tempdf['revenue_yoy_average3'] > tempdf['revenue_yoy_average12'])
# # con2 = (tempdf['revenue_yoy'] > 0)
# # con3 = (tempdf['grossratio_yoy']>0)
# # con4 = (tempdf['profitratio_yoy']>0)
# con5 = (tempdf['close']>10)

# holdcon = (con0 & con1 & con2 & con5).astype(int)



tempdf.loc[:,'hold'] = holdcon
tempdf.loc[:,'diff'] = tempdf['hold'].diff().fillna(0)

tempdf.loc[(tempdf.index == '2015-01-11') & (tempdf['hold'] == 1),'diff'] = 1

# tempdf.loc[:,'buyprice'] = (tempdf['diff'] == 1).astype(int) * tempdf['close']
# tempdf.loc[:,'sellprice'] = (tempdf['diff'] == -1).astype(int) * tempdf['close']
# tempdf.loc[ (tempdf['diff'] == -1) & np.isnan(tempdf['close']) , 'sellprice' ] = -1

tempdf.loc[:,'buyprice'] = (tempdf['diff'] == 1).astype(int) * tempdf['adj_close']
tempdf.loc[:,'sellprice'] = (tempdf['diff'] == -1).astype(int) * tempdf['adj_close']
tempdf.loc[ (tempdf['diff'] == -1) & np.isnan(tempdf['adj_close']) , 'sellprice' ] = -1

tempdf.loc[:,'buyprice':'sellprice'] = tempdf.loc[:,'buyprice':'sellprice'].fillna(0)

# assert( len(tempdf[tempdf['hold'].diff().fillna(0)!=0])%2 == 0 )
print( 'sellprice len = ', len(tempdf[tempdf['sellprice']!=0]))
print( 'buyprice len = ',len(tempdf[tempdf['buyprice']!=0]))

ggdf = tempdf.groupby('stock_id').agg({'diff':'sum'})
ggdf.to_csv('summarydf.csv')
tempdf.to_csv('checkassert.csv')
(tempdf[tempdf['sellprice']!=0]).to_csv('sellprice.csv')
(tempdf[tempdf['buyprice']!=0]).to_csv('buyprice.csv')

tempdf.loc[tempdf['sellprice'] != 0,'profit'] = ((tempdf[tempdf['sellprice']!=0])['sellprice'].values/(tempdf[tempdf['buyprice']!=0])['buyprice'].values)-(0.004)
tempdf.loc[tempdf['sellprice'] == -1,'profit'] = 0
tempdf.loc[tempdf['sellprice'] != 0,'diffdays'] = (((tempdf[tempdf['diff']!=0].index.to_series().diff())[1::2])/np.timedelta64(1,'D')).astype(int)
# tempdf.loc[:,'profit'] = round(tempdf.loc[:,'profit'],2)
tempdf.loc[tempdf['sellprice'] != 0,'buydate'] = ((tempdf[tempdf['buyprice']!=0]).index).astype(str)
tempdf.loc[tempdf['sellprice'] != 0,'buyprice'] = (tempdf[tempdf['buyprice']!=0])['buyprice'].values
tempdf.loc[:,'tradingcount'] = abs(tempdf.loc[:,'diff'])

tempdf.loc[:,'net_buyprice'] = ( (tempdf['diff'] == 1).astype(int) * tempdf['adj_close'] )#new
tempdf.loc[:,'net_buyprice'] = ((tempdf['net_buyprice'].replace(['0', 0], np.nan)).fillna(method='pad')) #new
tempdf.loc[:,'net_ratio'] = tempdf['adj_close']/tempdf['net_buyprice'] #new

tempdf.to_csv('checkprofit.csv', encoding='utf_8_sig')
checkvaliddf = (tempdf.loc[((tempdf['hold']==1)|(tempdf['diff']==-1)),:])
checkvaliddf.to_csv('checkvaliddf.csv', encoding='utf_8_sig')

summarydf = tempdf.groupby('stock_id').agg({'tradingcount':'sum','profit':'mean','diffdays':'mean'})

summarydf.to_csv('summarydf.csv')

print('average profit = ', tempdf['profit'].mean())
print('average diffdays = ', tempdf['diffdays'].mean())


tEnd = time.time()
print( 'function cost %f sec' %(tEnd - tStart))

sellprice len =  128
buyprice len =  128
average profit =  1.06869340917501
average diffdays =  55.0625
function cost 5.206016 sec

In [16]:
# # testseries = df.groupby(['store', 'product']).agg({'sales': ['sum', 'count'], 
# #                                             'rating': 'mean'})
# testseries = tempdf.groupby('date').agg({
#                                          'hold':'sum',
#                                          'diff':'sum',
#                                         })
# print(testseries)

# for k in range(len(testseries)):
#     if(testseries.iloc[k,testseries.columns.get_loc('hold')]!=0 or testseries.iloc[k,testseries.columns.get_loc('diff')]<0):
#         print(testseries.iloc[k,:])
holdseries.loc[:,'net value'] = ((holdseries['net value'].replace(['0', 0], np.nan)).fillna(method='pad')) #new
print(holdseries)

NameError: name 'holdseries' is not defined

# point2

In [23]:
# # groupby example
# dfg = df.groupby(['store', 'product']).agg({'sales': ['sum', 'count'], 
#                                             'rating': 'mean'})

checkvaliddf = (tempdf.loc[((tempdf['hold']==1)|(tempdf['diff']==-1)),:]).copy()
holdseries = tempdf.groupby('date').agg({'hold':'sum','diff':'sum',})
holdseries.loc[:,'net value'] = 0
# average_profit_by_date = tempdf.groupby('date').agg({'hold':'sum'})


checkvaliddf.loc[:,'net_value'] = 0

total_net_value = 1

net_value_change_ratio = 0

for k in range(len(holdseries)):
    
    if(holdseries.iloc[k,holdseries.columns.get_loc('hold')]!=0 or holdseries.iloc[k,holdseries.columns.get_loc('diff')]<0):

        old_for_net_df_con = (checkvaliddf.index == holdseries.index[k-1])&(checkvaliddf['hold']==1)
        calculate_net_df_con = (checkvaliddf.index == holdseries.index[k]) & (((checkvaliddf['diff'] == 0) & (checkvaliddf['hold'] == 1)) | ((checkvaliddf['diff'] == -1) & (checkvaliddf['hold'] == 0)))
        new_df_con = (checkvaliddf.index == holdseries.index[k]) & (checkvaliddf['diff'] == 1) & (checkvaliddf['hold'] == 1)
        keep_df_con = (checkvaliddf.index == holdseries.index[k]) & (checkvaliddf['diff'] == 0) & (checkvaliddf['hold'] == 1)
        current_df_con = checkvaliddf.index == holdseries.index[k]
        
        current_df = checkvaliddf.loc[checkvaliddf.index == holdseries.index[k]]
        
        print(holdseries.index[k], '########## start current_df... ##########')
        print(checkvaliddf.loc[current_df_con,['stock_id','net_value','adj_close','hold']])
        
        hold_df_len = len(checkvaliddf.loc[new_df_con])+len(checkvaliddf.loc[keep_df_con])
    
#         if hold_df_len == 0:
#             assert(0)

        if(len(checkvaliddf.loc[calculate_net_df_con])!=0):
            if(len(checkvaliddf.loc[old_for_net_df_con])==0):
                assert(0)
                
            print(holdseries.index[k-1], 'old_for_net_df...')
            print(checkvaliddf.loc[old_for_net_df_con,['stock_id','net_value','adj_close','hold']])
            
            print(holdseries.index[k], 'calculate_net_df...')
            print(checkvaliddf.loc[calculate_net_df_con,['stock_id','net_value','adj_close','hold']])
            
            net_value_change_ratio = (checkvaliddf.loc[calculate_net_df_con])['adj_close'].values/(checkvaliddf.loc[old_for_net_df_con])['adj_close'].values
            print(holdseries.index[k], 'net_value_change_ratio = ', net_value_change_ratio)
            
            total_net_value = sum((checkvaliddf.loc[old_for_net_df_con])['net_value'].values*net_value_change_ratio)
            print(holdseries.index[k], 'net value sum = ', total_net_value)
            
        else:    
            print('----- len(calculate_net_df)==0 use old total_net_value, all stocks are new -----')
            print(holdseries.index[k], ', total_net_value = ', total_net_value)
    
        if hold_df_len > 0 :
            new_net_value = total_net_value*len(checkvaliddf.loc[new_df_con])/hold_df_len
            keep_net_value = total_net_value*len(checkvaliddf.loc[keep_df_con])/hold_df_len
        
        assert(hold_df_len == (len(checkvaliddf.loc[new_df_con])+len(checkvaliddf.loc[keep_df_con])))
        
        print('new_net_value = ', new_net_value)
        print('keep_net_value = ', keep_net_value)
    
        if len(checkvaliddf.loc[new_df_con])>0:
            checkvaliddf.loc[new_df_con,'net_value'] = new_net_value/len(checkvaliddf.loc[new_df_con])*0.996
        else:
            checkvaliddf.loc[new_df_con,'net_value'] = 0
            
        old_and_keep_con = (checkvaliddf['stock_id'].isin((checkvaliddf.loc[keep_df_con])['stock_id'].values)) & (old_for_net_df_con)        
        
        print('keep_df_con = ')
        print(checkvaliddf.loc[keep_df_con,['stock_id','net_value','adj_close','hold']])
        
        old_and_keep_con_net_value_change_ratio = (checkvaliddf.loc[keep_df_con])['adj_close'].values/(checkvaliddf.loc[old_and_keep_con])['adj_close'].values
        
        print('old_and_keep_con_net_value_change_ratio = ', old_and_keep_con_net_value_change_ratio)
        
        old_and_keep_net_value_sum_value = sum(checkvaliddf.loc[old_and_keep_con,'net_value'].values*old_and_keep_con_net_value_change_ratio)
        
        print('keep_net_value = ',keep_net_value)
        print('old_and_keep_net_value_sum_value = ',old_and_keep_net_value_sum_value)
        
        if old_and_keep_net_value_sum_value > 0:
            if keep_net_value/old_and_keep_net_value_sum_value > 1:   
                print('keep_net_value/old_and_keep_net_value_sum_value > 1')
                checkvaliddf.loc[keep_df_con,'net_value'] = checkvaliddf.loc[old_and_keep_con,'net_value'].values*old_and_keep_con_net_value_change_ratio*(1+(keep_net_value/old_and_keep_net_value_sum_value-1)*0.996)          
            else:
                checkvaliddf.loc[keep_df_con,'net_value'] = checkvaliddf.loc[old_and_keep_con,'net_value'].values*old_and_keep_con_net_value_change_ratio*keep_net_value/old_and_keep_net_value_sum_value
        else:
            checkvaliddf.loc[keep_df_con,'net_value'] = 0
        
        print(holdseries.index[k], 'final current_df...')
        print(checkvaliddf.loc[current_df_con,['stock_id','net_value','adj_close','hold']]) 
        if hold_df_len > 0:
            total_net_value = (checkvaliddf.loc[current_df_con,'net_value']).sum()
        print(holdseries.index[k], '********** final net value = ', (checkvaliddf.loc[current_df_con,'net_value']).sum(), '**********' )
        print(' ')
        print(' ')
    
    holdseries.iloc[k,holdseries.columns.get_loc('net value')] = total_net_value
    
    
#     if(k==25):
#         break

2015-01-11 00:00:00 ########## start current_df... ##########
           stock_id  net_value   adj_close  hold
date
2015-01-11     1227          0  191.382639     1
2015-01-11     1323          0   60.568842     1
2015-01-11     1416          0   20.360883     1
2015-01-11     1452          0   20.420555     1
2015-01-11     1454          0   10.293122     1
...             ...        ...         ...   ...
2015-01-11     9924          0   57.431209     1
2015-01-11     9927          0   69.607437     1
2015-01-11     9930          0  120.884256     1
2015-01-11     9943          0   55.187683     1
2015-01-11     9962          0   19.121029     1

[157 rows x 4 columns]
----- len(calculate_net_df)==0 use old total_net_value, all stocks are new -----
2015-01-11 00:00:00 , total_net_value =  1
new_net_value =  1.0
keep_net_value =  0.0
keep_df_con =
Empty DataFrame
Columns: [stock_id, net_value, adj_close, hold]
Index: []
old_and_keep_con_net_value_change_ratio =  []
keep_net_value =  0.0
old_and_keep_net_value_sum_value =  0
2015-01-11 00:00:00 final current_df...
           stock_id  net_value   adj_close  hold
date
2015-01-11     1227   0.006344  191.382639     1
2015-01-11     1323   0.006344   60.568842     1
2015-01-11     1416   0.006344   20.360883     1
2015-01-11     1452   0.006344   20.420555     1
2015-01-11     1454   0.006344   10.293122     1
...             ...        ...         ...   ...
2015-01-11     9924   0.006344   57.431209     1
2015-01-11     9927   0.006344   69.607437     1
2015-01-11     9930   0.006344  120.884256     1
2015-01-11     9943   0.006344   55.187683     1
2015-01-11     9962   0.006344   19.121029     1

[157 rows x 4 columns]
2015-01-11 00:00:00 ********** final net value =  0.9960000000000002 **********


2015-02-11 00:00:00 ########## start current_df... ##########
           stock_id  net_value   adj_close  hold
date
2015-02-11     1215        0.0   42.785287     1
2015-02-11     1227        0.0  201.335673     1
2015-02-11     1323        0.0   61.926127     0
2015-02-11     1416        0.0   20.079656     1
2015-02-11     1452        0.0   21.567777     1
...             ...        ...         ...   ...
2015-02-11     9927        0.0   72.299437     1
2015-02-11     9930        0.0  123.975047     1
2015-02-11     9935        0.0    6.856505     1
2015-02-11     9943        0.0   54.625260     1
2015-02-11     9962        0.0   19.203448     0

[175 rows x 4 columns]
2015-01-11 00:00:00 old_for_net_df...
           stock_id  net_value   adj_close  hold
date
2015-01-11     1227   0.006344  191.382639     1
2015-01-11     1323   0.006344   60.568842     1
2015-01-11     1416   0.006344   20.360883     1
2015-01-11     1452   0.006344   20.420555     1
2015-01-11     1454   0.006344   10.293122     1
...             ...        ...         ...   ...
2015-01-11     9924   0.006344   57.431209     1
2015-01-11     9927   0.006344   69.607437     1
2015-01-11     9930   0.006344  120.884256     1
2015-01-11     9943   0.006344   55.187683     1
2015-01-11     9962   0.006344   19.121029     1

[157 rows x 4 columns]
2015-02-11 00:00:00 calculate_net_df...
           stock_id  net_value   adj_close  hold
date
2015-02-11     1227        0.0  201.335673     1
2015-02-11     1323        0.0   61.926127     0
2015-02-11     1416        0.0   20.079656     1
2015-02-11     1452        0.0   21.567777     1
2015-02-11     1454        0.0   10.484444     1
...             ...        ...         ...   ...
2015-02-11     9924        0.0   60.768191     0
2015-02-11     9927        0.0   72.299437     1
2015-02-11     9930        0.0  123.975047     1
2015-02-11     9943        0.0   54.625260     1
2015-02-11     9962        0.0   19.203448     0

[157 rows x 4 columns]
2015-02-11 00:00:00 net_value_change_ratio =  [1.05200594 1.02240896 0.98618785 1.05617978 1.01858736 1.00560224
 0.98780488 0.95187166 1.56428571 0.97941176 1.03955696 0.9587156
 0.97820823 0.95728643 1.00874636 1.0013459  0.98214286 1.00173913
 0.94414414 1.         0.99215686 0.96069869 0.98214286 0.99635036
 1.13677812 0.9787234  0.97590361 1.17667238 1.03180212 1.02238806
 1.10447761 0.98496241 0.9537037  0.91836735 1.10883483 0.92059839
 0.96209913 0.88669951 0.92086331 0.88252149 1.07984791 1.03108808
 1.11764706 1.06455542 0.99770115 1.01392758 1.         1.01948052
 0.91621622 1.02676399 1.03883495 0.98518519 1.01092044 1.31412104
 1.04693878 1.06962025 1.04496403 1.11372549 1.         0.99316239
 0.97191888 1.01201201 1.00958466 0.96221662 0.97294372 0.91666667
 0.90143737 0.97135417 0.93294461 1.02964119 0.98944591 0.99450549
 1.14957265 0.95428571 0.95054945 0.97771953 0.98778833 0.85106383
 2.05833333 0.99709724 0.93854749 1.04710145 0.92561983 0.95220588
 0.89183673 0.99107143 0.96774194 0.92605634 0.94936709 1.01830283
 1.         0.95744681 0.98947368 1.14163823 0.95735294 0.98614319
 0.97357441 0.92884615 0.9537037  1.28867403 0.96046512 0.9875
 0.70410959 0.8907563  1.01780415 1.07987711 1.02622577 1.06684142
 0.91775924 0.97368421 0.93665158 1.08058608 1.00224215 0.96947368
 0.9017341  1.12763466 1.00411523 0.99848024 1.00884956 1.19206681
 0.97994269 0.90776699 0.97527473 0.9952     1.030837   1.05345502
 0.99595142 1.00821355 0.97913043 1.06324973 0.97745902 0.93565684
 0.98784195 1.         0.97058824 1.04032258 1.02317291 1.00605327
 0.90628853 0.99236641 1.03869048 1.07786885 1.15252294 0.98934281
 1.07003891 1.1465721  1.09411765 0.95609756 0.99337748 1.00298507
 1.09574468 0.89377289 1.05810398 1.03867403 1.02556818 0.98980892
 1.00431034]
2015-02-11 00:00:00 net value sum =  1.0084131234460971
new_net_value =  0.12518231877261896
keep_net_value =  0.8832308046734781
keep_df_con =
           stock_id  net_value   adj_close  hold
date
2015-02-11     1227        0.0  201.335673     1
2015-02-11     1416        0.0   20.079656     1
2015-02-11     1452        0.0   21.567777     1
2015-02-11     1454        0.0   10.484444     1
2015-02-11     1477        0.0  300.510969     1
...             ...        ...         ...   ...
2015-02-11     8433        0.0   48.738376     1
2015-02-11     8436        0.0   85.003381     1
2015-02-11     9927        0.0   72.299437     1
2015-02-11     9930        0.0  123.975047     1
2015-02-11     9943        0.0   54.625260     1

[127 rows x 4 columns]
old_and_keep_con_net_value_change_ratio =  [1.05200594 0.98618785 1.05617978 1.01858736 1.00560224 0.95187166
 0.97941176 1.03955696 0.9587156  0.95728643 1.00874636 1.0013459
 0.98214286 1.00173913 0.94414414 1.         0.96069869 0.98214286
 1.13677812 0.9787234  1.03180212 1.02238806 1.10447761 0.9537037
 0.91836735 1.10883483 0.92059839 0.92086331 0.88252149 1.07984791
 1.03108808 1.06455542 0.99770115 1.01392758 1.         1.01948052
 0.91621622 1.02676399 1.03883495 0.98518519 1.01092044 1.31412104
 1.04693878 1.06962025 1.04496403 1.11372549 1.         0.99316239
 0.97191888 1.01201201 1.00958466 0.96221662 0.97294372 0.90143737
 0.97135417 0.93294461 1.02964119 0.98944591 1.14957265 0.95428571
 0.95054945 0.97771953 0.98778833 0.85106383 2.05833333 0.99709724
 0.93854749 1.04710145 0.92561983 0.95220588 0.89183673 0.99107143
 1.01830283 1.         0.95744681 0.98947368 1.14163823 0.95735294
 0.98614319 0.97357441 0.92884615 0.9537037  1.28867403 0.96046512
 0.9875     1.01780415 1.06684142 0.91775924 0.97368421 0.93665158
 1.08058608 0.96947368 1.12763466 1.00411523 0.99848024 1.00884956
 1.19206681 0.97994269 0.97527473 0.9952     1.030837   1.05345502
 0.99595142 1.00821355 0.97913043 1.06324973 0.97745902 0.93565684
 0.98784195 1.         1.04032258 1.00605327 0.90628853 0.99236641
 1.03869048 1.07786885 1.15252294 0.98934281 1.1465721  1.09411765
 0.95609756 0.99337748 1.09574468 0.89377289 1.03867403 1.02556818
 0.98980892]
keep_net_value =  0.8832308046734781
old_and_keep_net_value_sum_value =  0.8178317074606648
keep_net_value/old_and_keep_net_value_sum_value > 1
2015-02-11 00:00:00 final current_df...
           stock_id  net_value   adj_close  hold
date
2015-02-11     1215   0.006927   42.785287     1
2015-02-11     1227   0.007205  201.335673     1
2015-02-11     1323   0.000000   61.926127     0
2015-02-11     1416   0.006755   20.079656     1
2015-02-11     1452   0.007234   21.567777     1
...             ...        ...         ...   ...
2015-02-11     9927   0.007114   72.299437     1
2015-02-11     9930   0.007024  123.975047     1
2015-02-11     9935   0.006927    6.856505     1
2015-02-11     9943   0.006779   54.625260     1
2015-02-11     9962   0.000000   19.203448     0

[175 rows x 4 columns]
2015-02-11 00:00:00 ********** final net value =  1.0076507977821554 **********


2015-03-11 00:00:00 ########## start current_df... ##########
           stock_id  net_value   adj_close  hold
date
2015-03-11     1108        0.0   12.041395     1
2015-03-11     1215        0.0   40.705447     1
2015-03-11     1219        0.0   20.282247     1
2015-03-11     1227        0.0  220.104253     1
2015-03-11     1416        0.0   20.473374     1
...             ...        ...         ...   ...
2015-03-11     9925        0.0   66.190284     1
2015-03-11     9927        0.0   73.260866     1
2015-03-11     9930        0.0  123.803336     1
2015-03-11     9935        0.0    6.906710     1
2015-03-11     9943        0.0   57.929491     1

[173 rows x 4 columns]
2015-02-11 00:00:00 old_for_net_df...
           stock_id  net_value   adj_close  hold
date
2015-02-11     1215   0.006927   42.785287     1
2015-02-11     1227   0.007205  201.335673     1
2015-02-11     1416   0.006755   20.079656     1
2015-02-11     1452   0.007234   21.567777     1
2015-02-11     1454   0.006977   10.484444     1
...             ...        ...         ...   ...
2015-02-11     9925   0.006927   63.657075     1
2015-02-11     9927   0.007114   72.299437     1
2015-02-11     9930   0.007024  123.975047     1
2015-02-11     9935   0.006927    6.856505     1
2015-02-11     9943   0.006779   54.625260     1

[145 rows x 4 columns]
2015-03-11 00:00:00 calculate_net_df...
           stock_id  net_value   adj_close  hold
date
2015-03-11     1215        0.0   40.705447     1
2015-03-11     1227        0.0  220.104253     1
2015-03-11     1416        0.0   20.473374     1
2015-03-11     1452        0.0   29.445370     1
2015-03-11     1454        0.0   11.287996     1
...             ...        ...         ...   ...
2015-03-11     9925        0.0   66.190284     1
2015-03-11     9927        0.0   73.260866     1
2015-03-11     9930        0.0  123.803336     1
2015-03-11     9935        0.0    6.906710     1
2015-03-11     9943        0.0   57.929491     1

[145 rows x 4 columns]
2015-03-11 00:00:00 net_value_change_ratio =  [0.95138889 1.09322034 1.01960784 1.36524823 1.07664234 1.10584958
 1.00684932 1.00786517 1.04029304 1.03603604 1.02360877 1.04414003
 1.01435407 1.01363073 1.04855643 1.01156069 1.04032258 1.00909091
 1.01909722 1.01526718 1.13973799 0.96818182 0.97727273 0.93315508
 1.05279503 1.03424658 1.13138686 0.98648649 1.02427184 0.98333333
 1.05196305 1.         1.02213542 1.12012987 1.0915493  0.96733668
 1.13729977 0.99654378 1.06043956 1.01937984 1.06369427 0.89380531
 0.992891   1.02262931 1.18691589 1.10150376 1.19444444 1.06798246
 1.07212476 1.01183432 1.02753873 1.0528169  1.04157549 1.04475043
 1.04975923 1.04154303 1.00395778 1.05696203 1.         0.97886541
 1.00683371 0.96246649 1.10625    1.08636364 0.992      0.99256506
 0.98203593 0.98265896 1.03351206 1.01098901 1.13333333 1.2145749
 1.19359534 1.01190476 1.05190311 1.01190476 1.07722008 1.09839817
 1.10507246 0.91591592 1.07843137 1.13913043 0.97111111 1.02030457
 1.06382979 1.05829596 1.14592934 1.0117096  1.02142857 1.20600414
 0.97572816 1.3397642  1.02035623 1.21273885 1.         1.10548523
 1.08017493 1.08968059 1.00649351 0.98064516 1.05574324 0.99516908
 1.05084746 1.12920738 1.01386139 1.04257529 1.0204918  1.09284627
 1.00219298 1.08756567 1.02046784 0.99014085 1.0096463  1.01709402
 0.97153465 1.08130081 1.15682281 0.95914742 1.09948718 0.99161426
 0.95702006 0.96307692 1.17406542 0.98151951 1.06046512 1.02888087
 1.00680272 1.12307692 1.00143266 0.99239544 1.09950249 1.07360862
 0.95360825 0.9811828  1.2372449  1.11111111 0.98709677 1.0038835
 1.03278689 1.02811245 1.03979461 1.01329787 0.99861496 1.00732218
 1.06048906]
2015-03-11 00:00:00 net value sum =  1.0565074037784437
new_net_value =  0.20832540356194665
keep_net_value =  0.848182000216497
keep_df_con =
           stock_id  net_value   adj_close  hold
date
2015-03-11     1215        0.0   40.705447     1
2015-03-11     1227        0.0  220.104253     1
2015-03-11     1416        0.0   20.473374     1
2015-03-11     1452        0.0   29.445370     1
2015-03-11     1454        0.0   11.287996     1
...             ...        ...         ...   ...
2015-03-11     9925        0.0   66.190284     1
2015-03-11     9927        0.0   73.260866     1
2015-03-11     9930        0.0  123.803336     1
2015-03-11     9935        0.0    6.906710     1
2015-03-11     9943        0.0   57.929491     1

[114 rows x 4 columns]
old_and_keep_con_net_value_change_ratio =  [0.95138889 1.09322034 1.01960784 1.36524823 1.07664234 1.00786517
 1.03603604 1.04414003 1.04855643 1.04032258 1.00909091 1.01909722
 1.01526718 1.13973799 1.05279503 1.03424658 0.98648649 0.98333333
 1.         1.12012987 1.0915493  0.96733668 1.13729977 0.99654378
 1.06043956 1.01937984 1.06369427 0.89380531 0.992891   1.02262931
 1.10150376 1.19444444 1.06798246 1.07212476 1.01183432 1.02753873
 1.0528169  1.04157549 1.04154303 1.00395778 1.05696203 1.
 0.97886541 1.00683371 0.96246649 1.10625    1.08636364 0.992
 0.98203593 1.01098901 1.13333333 1.2145749  1.19359534 1.01190476
 1.05190311 1.01190476 1.07722008 1.09839817 1.10507246 0.91591592
 1.07843137 1.13913043 0.97111111 1.02030457 1.06382979 1.05829596
 1.14592934 1.02142857 1.20600414 0.97572816 1.3397642  1.21273885
 1.         1.10548523 1.08017493 1.08968059 1.00649351 0.98064516
 1.05574324 0.99516908 1.05084746 1.12920738 1.01386139 1.04257529
 1.09284627 1.00219298 1.08756567 0.99014085 1.01709402 0.97153465
 1.15682281 0.95914742 1.09948718 0.95702006 0.96307692 1.17406542
 1.02888087 1.12307692 1.00143266 0.99239544 1.09950249 1.07360862
 0.9811828  1.2372449  1.11111111 0.98709677 1.0038835  1.03278689
 1.02811245 1.03979461 1.01329787 0.99861496 1.00732218 1.06048906]
keep_net_value =  0.848182000216497
old_and_keep_net_value_sum_value =  0.8372569593272162
keep_net_value/old_and_keep_net_value_sum_value > 1
2015-03-11 00:00:00 final current_df...
           stock_id  net_value   adj_close  hold
date
2015-03-11     1108   0.007410   12.041395     1
2015-03-11     1215   0.006676   40.705447     1
2015-03-11     1219   0.007410   20.282247     1
2015-03-11     1227   0.007979  220.104253     1
2015-03-11     1416   0.006977   20.473374     1
...             ...        ...         ...   ...
2015-03-11     9925   0.007296   66.190284     1
2015-03-11     9927   0.007302   73.260866     1
2015-03-11     9930   0.007106  123.803336     1
2015-03-11     9935   0.007068    6.906710     1
2015-03-11     9943   0.007283   57.929491     1

[173 rows x 4 columns]
2015-03-11 00:00:00 ********** final net value =  1.0556304020006388 **********


2015-04-11 00:00:00 ########## start current_df... ##########
           stock_id  net_value   adj_close  hold
date
2015-04-11     1108        0.0   12.620308     1
2015-04-11     1215        0.0   43.305248     0
2015-04-11     1219        0.0   20.826737     0
2015-04-11     1225        0.0   26.560277     1
2015-04-11     1227        0.0  215.838667     1
...             ...        ...         ...   ...
2015-04-11     9933        0.0   89.680773     1
2015-04-11     9935        0.0    6.885193     0
2015-04-11     9941        0.0  118.637425     1
2015-04-11     9943        0.0   61.233722     1
2015-04-11     9958        0.0   12.810666     1

[220 rows x 4 columns]
2015-03-11 00:00:00 old_for_net_df...
           stock_id  net_value   adj_close  hold
date
2015-03-11     1108   0.007410   12.041395     1
2015-03-11     1215   0.006676   40.705447     1
2015-03-11     1219   0.007410   20.282247     1
2015-03-11     1227   0.007979  220.104253     1
2015-03-11     1416   0.006977   20.473374     1
...             ...        ...         ...   ...
2015-03-11     9925   0.007296   66.190284     1
2015-03-11     9927   0.007302   73.260866     1
2015-03-11     9930   0.007106  123.803336     1
2015-03-11     9935   0.007068    6.906710     1
2015-03-11     9943   0.007283   57.929491     1

[142 rows x 4 columns]
2015-04-11 00:00:00 calculate_net_df...
           stock_id  net_value   adj_close  hold
date
2015-04-11     1108        0.0   12.620308     1
2015-04-11     1215        0.0   43.305248     0
2015-04-11     1219        0.0   20.826737     0
2015-04-11     1227        0.0  215.838667     1
2015-04-11     1416        0.0   20.192147     0
...             ...        ...         ...   ...
2015-04-11     9925        0.0   66.026851     0
2015-04-11     9927        0.0   76.433580     0
2015-04-11     9930        0.0  139.085579     0
2015-04-11     9935        0.0    6.885193     0
2015-04-11     9943        0.0   61.233722     1

[142 rows x 4 columns]
2015-04-11 00:00:00 net_value_change_ratio =  [1.04807692 1.06386861 1.02684564 0.98062016 0.98626374 1.28051948
 1.21468927 1.06865672 1.08249721 1.08866995 1.10724638 1.00291545
 1.0952381  0.99753086 1.05381727 0.99354005 1.01501502 1.19250426
 1.03007519 0.93594306 1.1532567  1.09144543 1.38410596 1.00684932
 0.92372881 1.1        1.00253165 0.95652174 0.96129032 0.94285714
 1.01609658 1.02312139 1.12435233 0.98098859 1.02095808 0.98349835
 0.98090692 0.92729189 0.96245734 0.9870801  1.12525667 0.94
 1.01052632 0.99329983 0.95427196 1.17056856 0.98529412 1.07692308
 0.97634691 1.12874251 0.9947644  1.18939394 1.00340909 0.98813056
 1.04524887 0.99721448 1.00564972 1.14569536 1.013947   1.07526882
 0.93820225 0.97674419 1.00737101 1.07272727 1.18902439 1.01358696
 0.79411765 0.99864682 0.78333333 1.0097561  1.04705882 1.00328947
 0.99411765 1.07168459 0.98854167 1.01092896 1.         0.74242424
 0.99618321 0.63844394 1.04726368 0.95777778 1.11440678 1.11914894
 0.88064516 1.02380952 1.12734584 1.00839161 1.08154506 0.94029851
 0.96892655 1.4768     1.20798319 1.1283293  0.98473282 0.94893617
 1.02024291 1.20604915 0.97970688 0.9883871  1.02083333 1.12
 0.98058252 0.91774194 1.15865385 0.93811075 0.9609375  1.17928287
 0.93175487 0.97811816 1.33977456 0.88865323 1.01669759 0.92318634
 1.02521008 1.10573248 1.04225352 1.01851852 1.15858209 0.98802395
 0.98402556 0.9840796  1.08654971 0.77226027 1.01716738 1.01532567
 0.93665158 1.10200669 1.08163265 0.92054795 0.97525773 1.054
 1.07189542 1.00580271 1.11111111 1.09179687 0.98465473 0.99753086
 1.04330709 1.12343967 0.99688474 1.05703883]
2015-04-11 00:00:00 net value sum =  1.0887128883558785
new_net_value =  0.624408862439401
keep_net_value =  0.4643040259164776
keep_df_con =
           stock_id  net_value   adj_close  hold
date
2015-04-11     1108        0.0   12.620308     1
2015-04-11     1227        0.0  215.838667     1
2015-04-11     1452        0.0   37.705369     1
2015-04-11     1454        0.0   13.711408     1
2015-04-11     1460        0.0   19.120438     1
2015-04-11     1708        0.0   62.096895     1
2015-04-11     1730        0.0   54.683368     1
2015-04-11     1787        0.0   34.616963     1
2015-04-11     2108        0.0   39.970784     1
2015-04-11     2330        0.0  214.052259     1
2015-04-11     2354        0.0  198.275600     1
2015-04-11     2359        0.0   21.750665     1
2015-04-11     2383        0.0   88.122176     1
2015-04-11     2409        0.0   18.883629     1
2015-04-11     2449        0.0   45.330145     1
2015-04-11     2455        0.0   87.570753     1
2015-04-11     2456        0.0   66.792650     1
2015-04-11     2459        0.0   67.513987     1

# point3

In [ ]:
# print((checkvaliddf.index.unique().sort_values())[7])

checkvaliddf = (tempdf.loc[((tempdf['hold']==1)|(tempdf['diff']==-1)),:]).copy()
holdseries = tempdf.groupby('date').agg({'hold':'sum'})
average_profit_by_date = tempdf.groupby('date').agg({'hold':'sum'})

# print(holdseries)

# print(holdseries.iloc[50,holdseries.columns.get_loc('hold')]) holdseries.iloc[i,holdseries.columns.get_loc('hold')]!=0

# print(holdseries.iloc[])
# for i in range(len(checkvaliddf)):
#     for j in range(len(holdseries)):
#         if(checkvaliddf.index[i] == holdseries.index[k]):
#         print(checkvaliddf.index[i] )
#     if (finaldf.revenue_status).iloc[i] == -1:

# tempdf.loc[(tempdf.index == '2013-6-11') & (tempdf['hold'] == 1),'diff'] = 1

# tempdf.loc[tempdf.index == '2014-6-11','test'] = 1
# print(checkvaliddf.loc[checkvaliddf.index == '2014-6-11',:])
# print(tempdf)

# firstround = True

checkvaliddf.loc[:,'net_value'] = 0
checkvaliddf.loc[checkvaliddf.index == '2014-6-11','net_value'] = 1

total_net_value = 0

for k in range(len(holdseries)):
    
    if(holdseries.iloc[k,holdseries.columns.get_loc('hold')]!=0):
        
        if (k-1)>=0:
            last_for_net_df = checkvaliddf.loc[checkvaliddf.index == holdseries.index[k-1]]
            last_for_net_df = last_for_net_df.loc[last_for_net_df['hold']==1,:]
            
        current_df = checkvaliddf.loc[checkvaliddf.index == holdseries.index[k]]
        
        print(holdseries.index[k], 'current_df...')
        print(current_df)
        
        current_df.loc[:,'net_value'] = 5000
        
        print(current_df)
        print(checkvaliddf.loc[checkvaliddf.index == holdseries.index[k]])
        
        new_df = current_df.loc[(current_df['diff'] == 1) & (current_df['hold'] == 1),:]
        keep_df = current_df.loc[(current_df['diff'] == 0) & (current_df['hold'] == 1),:]
        hold_df_len = len(new_df)+len(keep_df)
        
        calculate_net_df = current_df.loc[((current_df['diff'] == 0) & (current_df['hold'] == 1)) | ((current_df['diff'] == -1) & (current_df['hold'] == 0)),:]

        if(len(calculate_net_df)!=0):
            if(len(last_for_net_df)==0):
                assert(0)
            print(holdseries.index[k], 'calculate_net_df...')
            print(calculate_net_df)
            print(holdseries.index[k-1], 'last_for_net_df...')
            print(last_for_net_df)
            print(last_for_net_df['net_value'].values*calculate_net_df['net_ratio'].values)
            total_net_value = sum(last_for_net_df['net_value'].values*calculate_net_df['net_ratio'].values)
            print(holdseries.index[k], 'net value sum = ', total_net_value)
        else:    
            print('len(calculate_net_df)==0 use old total_net_value')
            print(holdseries.index[k], ', total_net_value = ', total_net_value)
        
        calculate_net_df.loc[:,'net_value'] = 10000 #last_for_net_df['net_value'].values*calculate_net_df['net_ratio'].values
        new_df.loc[:,'net_value'] = total_net_value/hold_df_len
        keep_df.loc[:,'net_value'] = keep_df.loc[:,'net_value']*len(calculate_net_df)/hold_df_len

        print(holdseries.index[k], 'calculate_net_df...')
        print(calculate_net_df)     
        
        print(holdseries.index[k], 'current_df...')
        print(current_df)        
        
        if(len(new_df)!=0):
            print(holdseries.index[k], 'new_df...')
            print(new_df)
            
        if(len(keep_df)!=0):
            print(holdseries.index[k], 'keep_df...')
            print(keep_df)            

        
#         if(len(last_for_net_df)!=0):
#             print(holdseries.index[k], 'last_for_net_df...')
#             print(last_for_net_df['net_value'])            
        
#     print(holdseries.iloc[k,:])
#     print(holdseries.index[k])
# #         print(holdseries.iloc[k,holdseries.columns.get_loc('hold')])
#         checkvaliddf.loc[checkvaliddf.index == holdseries.index[k],'total_hold'] = holdseries.iloc[k,holdseries.columns.get_loc('hold')]
    if(k==15):
        break
# print(checkvaliddf)        
#         print(holdseries.iloc[k,:])

In [ ]:
# print(tempdf.loc[tempdf['sellprice'] != 0,'buydate'] = (tempdf[tempdf['buyprice']!=0]).index)
print((tempdf[tempdf['buyprice']!=0]).index)
print(len(tempdf[tempdf['buyprice']!=0]))
print(len(tempdf[tempdf['sellprice']!=0]))

In [ ]:
# tempdf = datasettest[datasettest['stock_id']=='3217']
# tempdf = datasettest[datasettest['stock_id'].isin(['3217', '2454'])]
# tempdf = datasettest[datasettest['stock_id']=='2454']

import time
tStart = time.time()
# stock_id = '1333'

# tempdf = datasettest[datasettest['stock_id']==stock_id].copy()

# print(stock_id)

tempdf = datasettest.copy()

con0 = ~np.isnan(tempdf['close']) & ~np.isnan(tempdf['close'])
# con1 = (tempdf.index != '2020-8-11')
con2 = (tempdf['revenue_yoy_average3'] > tempdf['revenue_yoy_average12'])
# con2 = (tempdf['revenue_yoy'] > 0)
con3 = (tempdf['grossratio_yoy']>0)
con4 = (tempdf['profitratio_yoy']>0)
con5 = (tempdf['close']>30)
con6 = tempdf['recent_rev']
con7 = tempdf['recent_rev2']
con8 = tempdf['recent_rev3']
con9 = tempdf['debt_smaller_than_50_oneyear']
con10 = tempdf['close_60'] > tempdf['close_120']
con11 = tempdf['close_120'] > tempdf['close_240']
con12 = tempdf['close_20'] > tempdf['close_60']
con13 = tempdf['R108_稅後淨利率']>5
con14 = tempdf['R11U_ROE綜合損益']>0
con15 = tempdf['R303_每股現金流量_average4']>1

holdcon = (con0 & con2 & con4 & con5 & con8 & con9 & con10 & con11 & con13 & con15).astype(int) #(con0 & con1 & con6 & con5).astype(int)

tempdf.loc[:,'hold'] = holdcon
tempdf.loc[:,'diff'] = tempdf['hold'].diff().fillna(0)




list1 = set(list(tempdf.loc[((tempdf.index == '2020-8-11') & (tempdf['hold'] == 1)),:]['stock_id']))
list2 = set(list(tempdf.loc[((tempdf.index == '2020-7-11') & (tempdf['hold'] == 0)),:]['stock_id']))
list3 = set(list(tempdf.loc[((tempdf.index == '2020-7-11') & (tempdf['hold'] == 1)),:]['stock_id']))

print(list1)
print(list3)

print(list1&list2)

list4 = set(list(tempdf.loc[((tempdf.index == '2020-5-11') & (tempdf['hold'] == 0)),:]['stock_id']))
list5 = set(list(tempdf.loc[((tempdf.index == '2020-6-11') & (tempdf['hold'] == 1)),:]['stock_id']))
# list6 = set(list(tempdf.loc[((tempdf.index == '2020-7-11') & (tempdf['hold'] == 1)),:]['stock_id']))

print(list4&list5)

# print(tempdf.loc[((tempdf.index == '2020-7-11') & (tempdf['hold'] == 1)),:])

# tempdf.loc[:,'buyprice'] = (tempdf['diff'] == 1).astype(int) * tempdf['close']
# tempdf.loc[:,'sellprice'] = (tempdf['diff'] == -1).astype(int) * tempdf['close']


# tempdf.loc[ (tempdf['diff'] == -1) & np.isnan(tempdf['close']) , 'sellprice' ] = -1

# tempdf.loc[:,'buyprice':'sellprice'] = tempdf.loc[:,'buyprice':'sellprice'].fillna(0)


# # assert( len(tempdf[tempdf['hold'].diff().fillna(0)!=0])%2 == 0 )
# print( 'sellprice len = ', len(tempdf[tempdf['sellprice']!=0]))
# print( 'buyprice len = ',len(tempdf[tempdf['buyprice']!=0]))

# ggdf = tempdf.groupby('stock_id').agg({'diff':'sum'})
# ggdf.to_csv('summarydf.csv')
# tempdf.to_csv('checkassert.csv')
# (tempdf[tempdf['sellprice']!=0]).to_csv('sellprice.csv')
# (tempdf[tempdf['buyprice']!=0]).to_csv('buyprice.csv')

# tempdf.loc[tempdf['sellprice'] != 0,'profit'] = ((tempdf[tempdf['sellprice']!=0])['sellprice'].values/(tempdf[tempdf['buyprice']!=0])['buyprice'].values)-(0.004)
# tempdf.loc[tempdf['sellprice'] == -1,'profit'] = 0
# tempdf.loc[tempdf['sellprice'] != 0,'diffdays'] = (((tempdf[tempdf['diff']!=0].index.to_series().diff())[1::2])/np.timedelta64(1,'D')).astype(int)
# # tempdf.loc[:,'profit'] = round(tempdf.loc[:,'profit'],2)
# tempdf.loc[tempdf['sellprice'] != 0,'buyprice'] = (tempdf[tempdf['buyprice']!=0])['buyprice'].values
# tempdf.loc[:,'tradingcount'] = abs(tempdf.loc[:,'diff'])


# tempdf.to_csv('checkprofit.csv', encoding='utf_8_sig')
# checkvaliddf = (tempdf.loc[((tempdf['hold']==1)|(tempdf['diff']==-1)),:])
# checkvaliddf.to_csv('checkvaliddf.csv', encoding='utf_8_sig')

# summarydf = tempdf.groupby('stock_id').agg({'tradingcount':'sum','profit':'mean','diffdays':'mean'})

# summarydf.to_csv('summarydf.csv')

# print('average profit = ', tempdf['profit'].mean())
# print('average diffdays = ', tempdf['diffdays'].mean())


tEnd = time.time()
print( 'function cost %f sec' %(tEnd - tStart))

In [ ]:
# print(tempdf.loc[(tempdf['stock_id']=='1101') & ((tempdf['hold']==1)|(tempdf['diff']==-1)),:])

In [ ]:
import matplotlib.pyplot as plt
holdseries = tempdf.groupby('date').agg({'hold':'sum'})
average_profit_by_date = tempdf.groupby('date').agg({'hold':'sum'})
print(holdseries)
holdseries = holdseries.rename(columns = {'hold':'Holding stock number'})
# print(holdseries)
# print(holdseries)
# print(holdseries.index.date())
holdseries = holdseries.reindex(index = holdseries.index.astype(str))
holdseries.plot(figsize = (20,10), grid=True, kind='bar')

In [ ]:
# tempdf = datasettest[datasettest['stock_id']=='3217']
# tempdf = datasettest[datasettest['stock_id'].isin(['3217', '2454'])]
# tempdf = datasettest[datasettest['stock_id']=='2454']

import time
tStart = time.time()



# stock_id = '1333'

# tempdf = datasettest[datasettest['stock_id']==stock_id].copy()

# print(stock_id)

tempdf = datasettest.copy()

con0 = ~np.isnan(tempdf['close']) & ~np.isnan(tempdf['close'])
con1 = ((tempdf['revenue_yoy_average3'] > tempdf['revenue_yoy_average12']))
con2 = (tempdf['grossratio_yoy']>0)
con3 = (tempdf.index != '2020-7-11')
con4 = (tempdf['profitratio_yoy']>0)
# con5 = (tempdf['profitratio_yoy']>0)

# holdcon = (con1 & con2 & con3 & con4).astype(int)
holdcon = (con0 & con1 & con3).astype(int)

# con0 = ~np.isnan(tempdf['close']) & ~np.isnan(tempdf['close'])
# con1 = (tempdf.index != '2020-7-11')
# con2 = ((tempdf['revenue_yoy_average3'] > tempdf['revenue_yoy_average12']))
# con3 = (tempdf['grossratio_yoy']>0)
# con4 = (tempdf['profitratio_yoy']>0)
# con5 = (tempdf['close']>100)

# holdcon = (con0 & con1 & con2 & con3 &con4 &con5).astype(int)

# tempdf.loc[:,'hold'] = holdcon.astype(int)
# tempdf.loc[:,'buyprice'] = (tempdf['hold'].diff() == 1).astype(int) * tempdf['close']
# tempdf.loc[:,'sellprice'] = (tempdf['hold'].diff() == -1).astype(int) * tempdf['close']
# tempdf.loc[:,'diff'] = tempdf['hold'].diff().fillna(0)

tempdf.loc[:,'hold'] = holdcon.astype(int)
tempdf.loc[:,'diff'] = tempdf['hold'].diff().fillna(0)

# print(tempdf)
# print(tempdf.loc[tempdf.index == '2013-6-11',:])
# print(tempdf.loc[tempdf['hold'] == 1,:])


tempdf.loc[(tempdf.index == '2013-6-11') & (tempdf['hold'] == 1),'diff'] = 1

tempdf.loc[:,'buyprice'] = (tempdf['diff'] == 1).astype(int) * tempdf['close']
tempdf.loc[:,'sellprice'] = (tempdf['diff'] == -1).astype(int) * tempdf['close']


# print( tempdf.loc[(tempdf['diff'] == -1) & np.isnan(tempdf['close'])] )

# print( tempdf.loc[(tempdf['diff'] == -1) & np.isnan(tempdf['close']),'sellprice'] )
tempdf.loc[ (tempdf['diff'] == -1) & np.isnan(tempdf['close']) , 'sellprice' ] = -1

tempdf.loc[:,'buyprice':'sellprice'] = tempdf.loc[:,'buyprice':'sellprice'].fillna(0)

# tempdf.loc[ (tempdf['diff'] == -1) & np.isnan(tempdf['close']) , 'buyprice' ] = -1
# print( datasettest[~np.isnan(datasettest['revenue_yoy'])] )

print(tempdf)

print(len(tempdf[tempdf['hold'].diff().fillna(0)!=0]))

# assert( len(tempdf[tempdf['hold'].diff().fillna(0)!=0])%2 == 0 )
print( 'sellprice len = ', len(tempdf[tempdf['sellprice']!=0]))
print( 'buyprice len = ',len(tempdf[tempdf['buyprice']!=0]))

ggdf = tempdf.groupby('stock_id').agg({'diff':'sum'})
ggdf.to_csv('summarydf.csv')


tempdf.to_csv('checkassert.csv')
(tempdf[tempdf['sellprice']!=0]).to_csv('sellprice.csv')
(tempdf[tempdf['buyprice']!=0]).to_csv('buyprice.csv')

# assert(len(tempdf[tempdf['sellprice']!=0]) ==  len(tempdf[tempdf['buyprice']!=0]))

tempdf.loc[tempdf['sellprice'] != 0,'profit'] = ((tempdf[tempdf['sellprice']!=0])['sellprice'].values/(tempdf[tempdf['buyprice']!=0])['buyprice'].values)-(0.004)
tempdf.loc[tempdf['sellprice'] == -1,'profit'] = 0
tempdf.loc[tempdf['sellprice'] != 0,'diffdays'] = (((tempdf[tempdf['diff']!=0].index.to_series().diff())[1::2])/np.timedelta64(1,'D')).astype(int)
# tempdf.loc[:,'profit'] = round(tempdf.loc[:,'profit'],2)
tempdf.loc[tempdf['sellprice'] != 0,'buyprice'] = (tempdf[tempdf['buyprice']!=0])['buyprice'].values
tempdf.loc[:,'tradingcount'] = abs(tempdf.loc[:,'diff'])

# selldate = finaldf.iloc[i,finaldf.columns.get_loc('Date')]
# thistime_diffdate = int((selldate-buydate)/ np.timedelta64(1, 'D'))

# tempdf.loc[:,'buyprice'] = (tempdf['hold'].diff() == 1).astype(int) * tempdf['close']

# print(testdf[~np.isnan(testdf['close'])])
# *round(((tempdf[tempdf['sellprice']!=0])['sellprice'].values/(tempdf[tempdf['buyprice']!=0])['buyprice'].values),2) 
# tempdf.loc[:,'buy_sell_price'] = abs((tempdf['hold'].diff()).fillna(0))*tempdf['close']


# tempdf.loc[:,'hold4'] = ((tempdf['hold3'].replace(['0', 0], np.nan)).fillna(method='ffill')).shift(1).copy()
# tempdf.loc[:,'hold5'] = tempdf['hold3']/tempdf['hold4']
# tempdf.loc[:,'hold6'] = (tempdf['hold2'].astype(int).diff() == -1).astype(int)
# tempdf.loc[:,'hold7'] = tempdf['hold5']*tempdf['hold6']

tempdf.to_csv('checkprofit.csv')

summarydf = tempdf.groupby('stock_id').agg({'tradingcount':'sum','profit':'mean','diffdays':'mean'})

summarydf.to_csv('summarydf.csv')

print('average profit = ', tempdf['profit'].mean())
print('average diffdays = ', tempdf['diffdays'].mean())


tEnd = time.time()
print( 'function cost %f sec' %(tEnd - tStart))  

# stocklist = ['3217', '2454', '2330', '4966', '3406' , '3324', '5274' ,'3552', '3373', '3234', '4128']

# stocklist = ['3217']

# tempdf = datasettest

# tempdf = datasettest[datasettest['stock_id']=='3217']

# for stock_id in datasettest['stock_id'].unique():
    


#     tempdf = datasettest[datasettest['stock_id'].isin(stocklist)]
#     tempdf = datasettest[datasettest['stock_id']==stock_id]
    
#     print(stock_id)

#     con1 = ((tempdf['revenue_yoy_average3'] > tempdf['revenue_yoy_average12']))
#     con2 = (tempdf['grossratio_yoy']>0)
#     con3 = (tempdf.index != '2020-7-11')

#     holdcon = (con1 & con2 & con3).astype(int)

#     tempdf.loc[:,'hold'] = holdcon.astype(int)
#     tempdf.loc[:,'buyprice'] = (tempdf['hold'].diff() == 1).astype(int) * tempdf['close']
#     tempdf.loc[:,'sellprice'] = (tempdf['hold'].diff() == -1).astype(int) * tempdf['close']

#     assert( len(tempdf[tempdf['hold'].diff().fillna(0)!=0])%2 == 0 )
#     # print( len(tempdf[tempdf['sellprice']!=0]))
#     # print( len(tempdf[tempdf['buyprice']!=0]))

#     # assert(len(tempdf[tempdf['sellprice']!=0]) ==  len(tempdf[tempdf['buyprice']!=0]))

#     tempdf.loc[tempdf['sellprice'] != 0,'profit'] = ((tempdf[tempdf['sellprice']!=0])['sellprice'].values/(tempdf[tempdf['buyprice']!=0])['buyprice'].values)
#     tempdf.loc[tempdf['sellprice'] != 0,'diffdays'] = (((tempdf[tempdf['hold'].diff().fillna(0)!=0].index.to_series().diff())[1::2])/np.timedelta64(1,'D')).astype(int)
#     # tempdf.loc[:,'profit'] = round(tempdf.loc[:,'profit'],2)
#     tempdf.loc[tempdf['sellprice'] != 0,'buyprice'] = (tempdf[tempdf['buyprice']!=0])['buyprice'].values


#     # selldate = finaldf.iloc[i,finaldf.columns.get_loc('Date')]
#     # thistime_diffdate = int((selldate-buydate)/ np.timedelta64(1, 'D'))

#     # tempdf.loc[:,'buyprice'] = (tempdf['hold'].diff() == 1).astype(int) * tempdf['close']

#     # print(testdf[~np.isnan(testdf['close'])])
#     # *round(((tempdf[tempdf['sellprice']!=0])['sellprice'].values/(tempdf[tempdf['buyprice']!=0])['buyprice'].values),2) 
#     # tempdf.loc[:,'buy_sell_price'] = abs((tempdf['hold'].diff()).fillna(0))*tempdf['close']


#     # tempdf.loc[:,'hold4'] = ((tempdf['hold3'].replace(['0', 0], np.nan)).fillna(method='ffill')).shift(1).copy()
#     # tempdf.loc[:,'hold5'] = tempdf['hold3']/tempdf['hold4']
#     # tempdf.loc[:,'hold6'] = (tempdf['hold2'].astype(int).diff() == -1).astype(int)
#     # tempdf.loc[:,'hold7'] = tempdf['hold5']*tempdf['hold6']

#     # print(tempdf['profit'].mean())

#     tEnd = time.time()
#     print( 'function cost %f sec' %(tEnd - tStart))   

    # print(tempdf)

In [ ]:
for stock_id in datasettest['stock_id'].unique():
    


#     tempdf = datasettest[datasettest['stock_id'].isin(stocklist)]
    tempdf = datasettest[datasettest['stock_id']==stock_id]
    
    print(stock_id)
    
    
    con1 = ((tempdf['revenue_yoy_average3'] > tempdf['revenue_yoy_average12']))
    con2 = (tempdf['grossratio_yoy']>0)
    con3 = (tempdf.index != '2020-7-11')
    con4 = (tempdf['profitratio_yoy']>0)

    holdcon = (con1 & con3).astype(int)

    tempdf.loc[:,'hold'] = holdcon.astype(int)
    tempdf.loc[:,'diff'] = tempdf['hold'].diff().fillna(0)



    tempdf.loc[(tempdf.index == '2013-6-11') & (tempdf['hold'] == 1),'diff'] = 1

    tempdf.loc[:,'buyprice'] = (tempdf['diff'] == 1).astype(int) * tempdf['close']
    tempdf.loc[:,'sellprice'] = (tempdf['diff'] == -1).astype(int) * tempdf['close']

    tempdf.loc[ (tempdf['diff'] == -1) & np.isnan(tempdf['close']) , 'sellprice' ] = -1

    tempdf.loc[:,'buyprice':'sellprice'] = tempdf.loc[:,'buyprice':'sellprice'].fillna(0)

    # tempdf.loc[ (tempdf['diff'] == -1) & np.isnan(tempdf['close']) , 'buyprice' ] = -1
    # print( datasettest[~np.isnan(datasettest['revenue_yoy'])] )

#     print(tempdf)

#     print(len(tempdf[tempdf['hold'].diff().fillna(0)!=0]))

    # assert( len(tempdf[tempdf['hold'].diff().fillna(0)!=0])%2 == 0 )
    print( 'sellprice len = ', len(tempdf[tempdf['sellprice']!=0]))
    print( 'buyprice len = ',len(tempdf[tempdf['buyprice']!=0]))

#     ggdf = tempdf.groupby('stock_id').agg({'diff':'sum'})
#     ggdf.to_csv('summarydf.csv')


#     tempdf.to_csv('checkassert.csv')

    # assert(len(tempdf[tempdf['sellprice']!=0]) ==  len(tempdf[tempdf['buyprice']!=0]))

    tempdf.loc[tempdf['sellprice'] != 0,'profit'] = ((tempdf[tempdf['sellprice']!=0])['sellprice'].values/(tempdf[tempdf['buyprice']!=0])['buyprice'].values)-(0.004)
    tempdf.loc[tempdf['sellprice'] == -1,'profit'] = 0
    tempdf.loc[tempdf['sellprice'] != 0,'diffdays'] = (((tempdf[tempdf['hold'].diff().fillna(0)!=0].index.to_series().diff())[1::2])/np.timedelta64(1,'D')).astype(int)
    tempdf.loc[tempdf['sellprice'] != 0,'buyprice'] = (tempdf[tempdf['buyprice']!=0])['buyprice'].values
    tempdf.loc[:,'tradingcount'] = abs(tempdf.loc[:,'diff'])

#     con1 = ((tempdf['revenue_yoy_average3'] > tempdf['revenue_yoy_average12']))
#     con2 = (tempdf['grossratio_yoy']>0)
#     con3 = (tempdf.index != '2020-7-11')

#     holdcon = (con1 & con2 & con3).astype(int)

#     tempdf.loc[:,'hold'] = holdcon.astype(int)
#     tempdf.loc[:,'buyprice'] = (tempdf['hold'].diff() == 1).astype(int) * tempdf['close']
#     tempdf.loc[:,'sellprice'] = (tempdf['hold'].diff() == -1).astype(int) * tempdf['close']

#     assert( len(tempdf[tempdf['sellprice']!=0]) == len(tempdf[tempdf['buyprice']!=0]) )
#     # print( len(tempdf[tempdf['sellprice']!=0]))
#     # print( len(tempdf[tempdf['buyprice']!=0]))

#     # assert(len(tempdf[tempdf['sellprice']!=0]) ==  len(tempdf[tempdf['buyprice']!=0]))

#     tempdf.loc[tempdf['sellprice'] != 0,'profit'] = ((tempdf[tempdf['sellprice']!=0])['sellprice'].values/(tempdf[tempdf['buyprice']!=0])['buyprice'].values)
#     tempdf.loc[tempdf['sellprice'] != 0,'diffdays'] = (((tempdf[tempdf['hold'].diff().fillna(0)!=0].index.to_series().diff())[1::2])/np.timedelta64(1,'D')).astype(int)
#     # tempdf.loc[:,'profit'] = round(tempdf.loc[:,'profit'],2)
#     tempdf.loc[tempdf['sellprice'] != 0,'buyprice'] = (tempdf[tempdf['buyprice']!=0])['buyprice'].values


    # selldate = finaldf.iloc[i,finaldf.columns.get_loc('Date')]
    # thistime_diffdate = int((selldate-buydate)/ np.timedelta64(1, 'D'))

    # tempdf.loc[:,'buyprice'] = (tempdf['hold'].diff() == 1).astype(int) * tempdf['close']

    # print(testdf[~np.isnan(testdf['close'])])
    # *round(((tempdf[tempdf['sellprice']!=0])['sellprice'].values/(tempdf[tempdf['buyprice']!=0])['buyprice'].values),2) 
    # tempdf.loc[:,'buy_sell_price'] = abs((tempdf['hold'].diff()).fillna(0))*tempdf['close']


    # tempdf.loc[:,'hold4'] = ((tempdf['hold3'].replace(['0', 0], np.nan)).fillna(method='ffill')).shift(1).copy()
    # tempdf.loc[:,'hold5'] = tempdf['hold3']/tempdf['hold4']
    # tempdf.loc[:,'hold6'] = (tempdf['hold2'].astype(int).diff() == -1).astype(int)
    # tempdf.loc[:,'hold7'] = tempdf['hold5']*tempdf['hold6']

    # print(tempdf['profit'].mean())

    tEnd = time.time()
    print( 'function cost %f sec' %(tEnd - tStart))

In [ ]:
# import time
#     tStart = time.time()
#     tEnd = time.time()
#     print( 'backtestfun cost %f sec' %(tEnd - tStart))   

datasettest = dataset[ dataset.index >= (profitratio_yoy.index)[0] ]
datasettest = datasettest[datasettest['stock_id']>='1101']

tempdf = datasettest[datasettest['stock_id']=='2454']
tempdf.loc[:,'hold'] = ((tempdf['revenue_yoy_average3'] > tempdf['revenue_yoy_average12']))
tempdf.loc[:,'hold1'] = (tempdf['grossratio_yoy']>0)
tempdf.loc[:,'hold2'] = (tempdf['grossratio_yoy']>0) & ((tempdf['revenue_yoy_average3'] > tempdf['revenue_yoy_average12'] ) )
tempdf.loc[:,'hold2']  = tempdf['hold2'].astype(int)
tempdf.loc[:,'hold3'] = abs((tempdf['hold2'].diff()).fillna(0))*tempdf['close']
tempdf.loc[:,'hold4'] = ((tempdf['hold3'].replace(['0', 0], np.nan)).fillna(method='ffill')).shift(1).copy()
tempdf.loc[:,'hold5'] = tempdf['hold3']/tempdf['hold4']
tempdf.loc[:,'hold6'] = (tempdf['hold2'].astype(int).diff() == -1).astype(int)
tempdf.loc[:,'hold7'] = tempdf['hold5']*tempdf['hold6']

# closestock = closestock.fillna(method='backfill')
# tempdf['hold'] = (tempdf['revenue_yoy_average3'] > tempdf['revenue_yoy_average12'] ) and tempdf['grossratio_yoy']>0 and tempdf['profitratio_yoy']>0
print(tempdf)
print(tempdf[tempdf['hold3']!=0])
# datasettest['ggg'] = datasettest['grossratio_yoy']>0
# print(datasettest.loc['2013-06-11'])
# print(datasettest[datasettest['stock_id']=='9985'])
# testdf = datasettest[datasettest['stock_id']=='9985']


# print(testdf[~np.isnan(testdf['close'])])
# print((testdf.apply(pd.to_numeric)).values.sum())      
# if ((testdf.apply(pd.to_numeric)).values.sum()):
#     print('testdf is empty')

# print(datasettest[datasettest['stock_id']=='2330'])

# print( datasettest[~np.isnan(datasettest['revenue_yoy'])] )
# import numpy as np
# print(datasettest)
# print(datasettest['revenue_yoy'])
# print(np.isnan((datasettest['revenue_yoy'])))

In [ ]:
print(tempdf[tempdf['hold7']!=0])

In [ ]:
2017-11-14    13.67
2018-03-31    -1.93
2018-05-15     0.71
2018-08-14    -1.21
2018-11-14    -9.60
2019-03-31     1.03
2019-05-15    -0.23
2019-08-14     4.16
2019-11-14    14.48
2020-03-31    22.82
2020-05-15    24.92

In [ ]:
from finlab.data import Data
import pandas as pd
from finlab import ml


data = Data()

rev = data.get("當月營收")
rev.index = rev.index.shift(1, "d")  #晚五天才知道營收
close = data.get("收盤價")
# close_per_week = close[::5]
adj_close = data.get_adj('收盤價')

close = close.T[(close.iloc[-150:].T.mean(axis=1)>70)].T
temp = close[::5]

# testlist = ['2454','2330']
# testclose = close[testlist]


# ===== trading frequency =====

every_month = rev.index
every_week = temp.index
trading_frequency = every_week

# ===== trading frequency =====

# ===== 計算features =====

def bias(n): #乖離率指標
    return close / close.rolling(n, min_periods=1).mean()

def acc(n): #加速度指標
    return close.shift(n) / (close.shift(2*n) + close) * 2

def rsv(n): #RSV指標
    l = close.rolling(n, min_periods=1).min()
    h = close.rolling(n, min_periods=1).max()
    
    return (close - l) / (h - l)

def mom(n):
    return (rev / rev.shift(1)).shift(n)

def yoy(n):
    return (rev / rev.shift(12)).shift(n)

def yoyacc(n):
    return ( (rev / rev.shift(12))/(rev / rev.shift(12)).shift(1) ).shift(n)

features = {
    'mom1': mom(1),
    'mom2': mom(2),
    'mom3': mom(3),
    'mom4': mom(4),
    'mom5': mom(5),
    'mom6': mom(6),
    'mom7': mom(7),
    'mom8': mom(8),
    'mom9': mom(9),  #why只到 mom 9???
    
    'bias5': bias(5),
    'bias10': bias(10),
    'bias20': bias(20),
    'bias60': bias(60),
    'bias120': bias(120),
    'bias240': bias(240),
    
    'acc5': acc(5),
    'acc10': acc(10),
    'acc20': acc(20),
    'acc60': acc(60),
    'acc120': acc(120),
    'acc240': acc(240),
    
    'yoy1': yoy(1),
    'yoy2': yoy(2),
    'yoy3': yoy(3),
    'yoy4': yoy(4),
    
    'yoyacc1': yoyacc(1),
    'yoyacc2': yoyacc(2),
}

# ===== 計算features =====

# ===== 組dataset =====

for name, f in features.items():
    features[name] = f.reindex(trading_frequency, method='ffill')
    
for name, f in features.items():
    features[name] = f.unstack()
    
dataset = pd.DataFrame(features)

feature_names = list(dataset.columns)

ml.add_profit_prediction(dataset)
ml.add_rank_prediction(dataset)

#神經網路容易被極值影響的網路, 此範例中刪除前百分之一

dataset_drop_extreme_case = ml.drop_extreme_case(dataset, 
    ['bias60', 'bias120', 'bias240', 'mom1', 'mom2', 'mom3', 'mom4', 'mom5', 'mom6'], thresh=0.01)

dataset_dropna = dataset_drop_extreme_case.dropna(how='any')
dataset_dropna = dataset_dropna.reset_index().set_index("date")

dataset_train = dataset_dropna[:'2015']
dataset_test = dataset_dropna['2016':]

In [ ]:
print(dataset_test)

In [ ]:
print(len((dataset_test[dataset_test['stock_id']=='1216'])))

print(dataset_test['stock_id'].unique())

In [ ]:
dates = sorted(list(set(dataset_test.index)))

forloopcount = 0

for d in dates:
    
    forloopcount = forloopcount + 1
    
    dataset_time = dataset_test.loc[d]
    
    print(dataset_time)
    
    if(forloopcount == 1):
        break

In [ ]:
dates = sorted(list(set(dataset.index)))

# print(dataset.loc['2007-04-23'])

In [ ]:
print(dataset[dataset['mom1']>1.1])

In [ ]:
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 200)
pd.set_option('display.width', 1000)

import matplotlib.pyplot as plt
import matplotlib.pyplot as plt

data = Data()
close1 = data.get("收盤價")
close2 = data.get_adj("收盤價")
plt.figure(1)
close1['8182'][-200:].plot()
plt.figure(2)
close2['8182'][-200:].plot()
# print(close2['8182'][-200:])

In [ ]:
from finlab.data import Data
import pandas as pd
from finlab import ml
import talib
import time

def create_backtest_dataset(backtest_period_after, isadj):
    tStart = time.time()
    
    data = Data()

#     rev = data.get("當月營收")
#     rev.index = rev.index.shift(5, "d")  #晚五天才知道營收
    
    if(isadj == True):
        close = data.get_adj("收盤價")
        openprice = data.get_adj("開盤價")
    else:
        close = data.get("收盤價")
        openprice = data.get("開盤價")        

#     adj_close = data.get_adj('收盤價')
    volume = data.get("成交股數")/1000
    base = data.get('股本合計')/10
    
    close = close[backtest_period_after:]
    volume = volume[backtest_period_after:]
    openprice = openprice[backtest_period_after:]
    
    rsi_9_temp = close.copy()
    rsi_9 = data.talib("RSI", timeperiod=9)
    rsi_9 = rsi_9[backtest_period_after:]
    rsi_9_final = rsi_9_temp
    rsi_9_final.loc[rsi_9.index,rsi_9.columns] = rsi_9
    
    rsi_25_temp = close.copy()
    rsi_25 = data.talib("RSI", timeperiod=25)
    rsi_25 = rsi_25[backtest_period_after:]
    rsi_25_final = rsi_25_temp
    rsi_25_final.loc[rsi_25.index,rsi_25.columns] = rsi_25
    
#     print('=================================================')
#     print(close)
#     print('=================================================')
#     print(volume)
#     print('=================================================')
#     print(rsifinal)
    
#     rsi = talib.RSI(close,9)
    

    # ===== trading frequency =====

    trading_frequency = close.index

    # ===== trading frequency =====

    # ===== 計算features =====

    def rsv(n): #RSV指標
        l = close.rolling(n, min_periods=1).min()
        h = close.rolling(n, min_periods=1).max()

        return (close - l) / (h - l)

    features = {
        'close' : close,
        'open' : openprice,
        'volume' : volume,
        'base' : base,
        'rsi_9' : rsi_9_final,
        'rsi_25' : rsi_25_final,
    }

    # ===== 計算features =====

    # ===== 組dataset =====

#     print(trading_frequency)
    
    for name, f in features.items():
        features[name] = f.reindex(trading_frequency, method='ffill')

    for name, f in features.items():
        features[name] = f.unstack()

    dataset = pd.DataFrame(features)

    feature_names = list(dataset.columns)
    
    dataset_drop_extreme_case = dataset

    dataset_dropna = dataset_drop_extreme_case.dropna(how='any')   
#     print('=================================================')
#     print(dataset_dropna)
#     print('=================================================')
    dataset_dropna = dataset_dropna.reset_index().set_index("date")
    stock_pool_number = len(dataset_dropna.groupby('stock_id').sum().index)
    print('===== stock pool number = ' + str(stock_pool_number) + ' =====' )

    dataset = dataset_dropna
    
    tEnd = time.time()
    print( 'create_backtest_dataset cost %f sec' %(tEnd - tStart))
    
    return dataset

    # ===== 組dataset =====

In [ ]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)
# pd.set_option('display.width', 1000)
dataset = create_backtest_dataset('2019-01-01')
# tempdata = dataset[dataset['stock_id'].isin(['2413'])]
# tempdata = dataset[dataset['stock_id'].isin(['6667'])].copy()
# tempdata.loc[:,'status'] = tempdata['rsi_9']>50
# tempdata.loc[:,'status'] = 1
# print(tempdata)

# tempdata = dataset[dataset['stock_id'].isin(['6667'])].copy()

# print(tempdata)

# print(tempdata.iloc[0,tempdata.columns.get_loc('close')])

# tempdata = tempdata.assign(status = 0)

# for i in range(len(tempdata)):
#     print(i)    
#     print(tempdata.index[i])
#     break

In [ ]:
# pd.set_option('display.max_columns', 30)
# pd.set_option('display.max_rows', 30)
# pd.set_option('display.width', 1000)

# print(dataset)
# print(list(dataset['stock_id'].unique()))

In [ ]:
totoal_stock_list = list(dataset['stock_id'].unique())

print(len(totoal_stock_list))

In [ ]:
def one_stock_backtest(current_stockid, dataset):
    
    trading_count, win_count, lose_count = (0,)*3
    profit = 1
    status1_i = 0
    status4_i = 0
    diff_i_1 = 0
    diff_i_4 = 0

    tempdata = dataset[dataset['stock_id'].isin([current_stockid])].copy()

    tempdata = tempdata.assign(high_rsi_1 = 0)
    tempdata = tempdata.assign(high_rsi_4 = 0)
    tempdata = tempdata.assign(high_price_1 = 0)
    tempdata = tempdata.assign(high_price_4 = 0)

    tempdata = tempdata.assign(status = 0)

    # print(tempdata)

    # for i in range(len(tempdata)):
    #     if (tempdata.close).iloc[i] > 80:
    #         tempdata.iloc[i:,-1] = (tempdata.close).iloc[i]
    # #         (tempdata.status).iloc[i:] = (tempdata.close).iloc[i]

    #         break

    # print(tempdata) 

    high_rsi_1, high_rsi_4, high_price_1, high_price_4, sell_price, buy_price = (0,)*6

    for i in range(len(tempdata)):

    #     print(i, ',' , (tempdata.close).iloc[i], (tempdata.rsi_9).iloc[i], (tempdata.status).iloc[i]) 

        if (tempdata.status).iloc[i] == 0 and (tempdata.rsi_9).iloc[i] > 80:

            tempdata.iloc[i:,-1] = 1

            high_rsi_1 = (tempdata.rsi_9).iloc[i]
            tempdata.iloc[i,tempdata.columns.get_loc('high_rsi_1')] = high_rsi_1

            high_price_1 = (tempdata.close).iloc[i]
            tempdata.iloc[i,tempdata.columns.get_loc('high_price_1')] = high_price_1
            
            status1_i=i

        elif (tempdata.status).iloc[i] == 1:

            if (tempdata.rsi_9).iloc[i] > high_rsi_1:
                high_rsi_1 = (tempdata.rsi_9).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_rsi_1')] = high_rsi_1
            if (tempdata.close).iloc[i] > high_price_1:
                high_price_1 = (tempdata.close).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_1')] = high_price_1

            if (tempdata.rsi_9).iloc[i] < 80 and (tempdata.rsi_9).iloc[i] < (tempdata.rsi_25).iloc[i]:
                tempdata.iloc[i:,-1] = 2            

        elif (tempdata.status).iloc[i] == 2:

            if (tempdata.rsi_9).iloc[i] < 70:
                tempdata.iloc[i:,-1] = 3

        elif (tempdata.status).iloc[i] == 3:

            if ((tempdata.close).iloc[i] > high_price_1) and ((tempdata.rsi_9).iloc[i] > (tempdata.rsi_25).iloc[i]):
                tempdata.iloc[i:,-1] = 4

                high_rsi_4 = (tempdata.rsi_9).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_rsi_4')] = high_rsi_4

                high_price_4 = (tempdata.close).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_4')] = high_price_4

        elif (tempdata.status).iloc[i] == 4:

            if (tempdata.rsi_9).iloc[i] > high_rsi_4:
                high_rsi_4 = (tempdata.rsi_9).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_rsi_4')] = high_rsi_4

            if (tempdata.close).iloc[i] > high_price_4:
                high_price_4 = (tempdata.close).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_4')] = high_price_4

    #         print( (tempdata.rsi_9).iloc[i], (tempdata.rsi_25).iloc[i], high_rsi_1, high_rsi_4, high_price_1, high_price_4 )     

            if (high_rsi_4 > high_rsi_1) or (high_rsi_4 > 80):

                tempdata.iloc[i:,-1] = 1

                high_rsi_1 = high_rsi_4
                tempdata.iloc[i,tempdata.columns.get_loc('high_rsi_1')] = high_rsi_1

                high_price_1 = high_price_4 if high_price_4 > high_price_1 else high_price_1
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_1')] = high_price_1

                continue

            if (tempdata.rsi_9).iloc[i] < (tempdata.rsi_25).iloc[i]:
                if (high_rsi_1>high_rsi_4) and (high_price_1<high_price_4):
                    tempdata.iloc[i:,-1] = 5
                    
            status4_i=i        

        elif (tempdata.status).iloc[i] == 5:
            tempdata.iloc[i:,-1] = 6
            print(tempdata.index[i], ', set sell_price = ', (tempdata.open).iloc[i])
            sell_price = (tempdata.open).iloc[i]
            trading_count = trading_count+1

        elif (tempdata.status).iloc[i] == 6:

            ### take profit

            if ((tempdata.open).iloc[i]/sell_price) < 0.9:
                buy_price = (tempdata.open).iloc[i]
                diff_i_1 = (-1)*(status1_i - i)
                diff_i_4 = (-1)*(status4_i - i)
                print(tempdata.index[i], ', point1 set buy_price = ', buy_price, 'profit = ', round(1+(1-((tempdata.open).iloc[i]/sell_price)),3), '%' ,'diff_i_1 = ', diff_i_1 ,'diff_i_4 = ', diff_i_4 )
                tempdata.iloc[i:,-1] = 0
                win_count = win_count+1
                profit = profit*(round(1+(1-((tempdata.open).iloc[i]/sell_price)),3))

            elif ((tempdata.close).iloc[i]/sell_price) < 0.9:
                buy_price = (tempdata.close).iloc[i]
                diff_i_1 = (-1)*(status1_i - i)
                diff_i_4 = (-1)*(status4_i - i)
                print(tempdata.index[i], ', point2 set buy_price = ', buy_price, 'profit = ', round(1+(1-((tempdata.close).iloc[i]/sell_price)),3), '%' ,'diff_i_1 = ', diff_i_1 ,'diff_i_4 = ', diff_i_4 )
                tempdata.iloc[i:,-1] = 0
                win_count = win_count+1
                profit = profit*(round(1+(1-((tempdata.close).iloc[i]/sell_price)),3))

            elif (tempdata.open).iloc[i] > (high_price_4+1) :    
                buy_price = (tempdata.open).iloc[i]
                diff_i_1 = (-1)*(status1_i - i)
                diff_i_4 = (-1)*(status4_i - i)
                print(tempdata.index[i], ', point3 set buy_price = ', buy_price, 'profit = ', round(1+(1-((tempdata.open).iloc[i]/sell_price)),3), '%' ,'diff_i_1 = ', diff_i_1 ,'diff_i_4 = ', diff_i_4 )
                tempdata.iloc[i:,-1] = 4    
                high_price_1 = high_price_4
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_1')] = high_price_1
                high_price_4 =(tempdata.open).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_4')] = high_price_4
                lose_count = lose_count+1
                profit = profit*(round(1+(1-((tempdata.open).iloc[i]/sell_price)),3))
                

            elif (tempdata.close).iloc[i] > (high_price_4+1) :    
                buy_price = (tempdata.close).iloc[i]
                diff_i_1 = (-1)*(status1_i - i)
                diff_i_4 = (-1)*(status4_i - i)
                print(tempdata.index[i], ', point4 set buy_price = ', buy_price, 'profit = ', round(1+(1-((tempdata.close).iloc[i]/sell_price)),3), '%' ,'diff_i_1 = ', diff_i_1 ,'diff_i_4 = ', diff_i_4 )
                tempdata.iloc[i:,-1] = 4        
                high_price_1 = high_price_4
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_1')] = high_price_1
                high_price_4 = (tempdata.close).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_4')] = high_price_4
                lose_count = lose_count+1
                profit = profit*(round(1+(1-((tempdata.close).iloc[i]/sell_price)),3))
                

            ### stop loss

        else :
            continue
    #         print('Error')

    #     print(i, ',' , tempdata.at[i,'close'], tempdata.at[i,'rsi_9'], tempdata.at[i,'status']) 


    print(tempdata)    
    
    print('current_stockid = ', current_stockid, ', trading_count = ', trading_count,', win_count = ', win_count,', lose_count = ', lose_count,', profit = ', profit)
    
    return trading_count, win_count, lose_count, profit

# trading_count, win_count, lose_count, profit

In [ ]:
def checkstockvolume(current_stockid):
    tempdata = dataset[dataset['stock_id'].isin([current_stockid])].copy()
    if(tempdata['volume'].mean()<200):
        return 1
    else:
        return 0
    
def checkstockprice(current_stockid):
    tempdata = dataset[dataset['stock_id'].isin([current_stockid])].copy()
    if(tempdata['close'].mean()<10):
        return 1
    else:
        return 0

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 1000)

dataset2 = create_backtest_dataset('2019-04-01', True)

one_stock_backtest('8182', dataset2)

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 1000)

dataset1 = create_backtest_dataset('2019-01-01', False)

one_stock_backtest('8182',dataset1)

In [ ]:
totoal_stock_list = list(dataset['stock_id'].unique())

totoal_stock_list = totoal_stock_list[500:600]

trading_count, win_count, lose_count = (0,)*3
profit = 1
total_stock_count,total_valid_stock_count, total_trading_count, total_win_count, total_lose_count = (0,)*5
total_profit = 1

for current_stockid in totoal_stock_list:
    
    if(checkstockvolume(current_stockid) == 1):
        print('current_stockid = ', current_stockid, ', average volume < 200')
        continue
        
    if(checkstockprice(current_stockid) == 1):
        print('current_stockid = ', current_stockid, ', average close < 10')
        continue    
    
    trading_count, win_count, lose_count, profit = one_stock_backtest(current_stockid)
    
    total_trading_count = total_trading_count+trading_count
    total_win_count = total_win_count+win_count
    total_lose_count = total_lose_count+lose_count
    total_profit = total_profit*profit

print('total_trading_count = ', total_trading_count, ', total_win_count = ', total_win_count
      , ', total_lose_count = ', total_lose_count, ', total_profit = ', total_profit
       )

In [ ]:
df = pd.DataFrame({'stock': ['6667','8182','6538'],'year': 0,'sale': 0})
print(df)

df1 = pd.DataFrame({'stock': ['total'],'year': 0,'sale': 0})

df = df.append(df1, ignore_index=True)

print(df)

df = df.set_index('stock')
print(df)

print(df.loc['6667'])

In [ ]:
tempdata = dataset[dataset['stock_id'].isin(['6667'])].copy()
print(tempdata)
print(tempdata['volume'].mean()>200)

In [ ]:

# tempdata = dataset[dataset['stock_id'].isin(['6667'])].copy()
# tempdata = dataset[dataset['stock_id'].isin(['6538'])].copy()
# tempdata.loc[:,'status'] = 0
# tempdata = dataset[dataset['stock_id'].isin(['8182'])].copy()

stocklist = ['6667','8182','6538']

for current_stockid in stocklist:

    print('current_stockid = ', current_stockid)

    tempdata = dataset[dataset['stock_id'].isin([current_stockid])].copy()

    tempdata = tempdata.assign(high_rsi_1 = 0)
    tempdata = tempdata.assign(high_rsi_4 = 0)
    tempdata = tempdata.assign(high_price_1 = 0)
    tempdata = tempdata.assign(high_price_4 = 0)

    tempdata = tempdata.assign(status = 0)

    # print(tempdata)

    # for i in range(len(tempdata)):
    #     if (tempdata.close).iloc[i] > 80:
    #         tempdata.iloc[i:,-1] = (tempdata.close).iloc[i]
    # #         (tempdata.status).iloc[i:] = (tempdata.close).iloc[i]

    #         break

    # print(tempdata) 

    high_rsi_1, high_rsi_4, high_price_1, high_price_4, sell_price, buy_price = (0,)*6

    for i in range(len(tempdata)):

    #     print(i, ',' , (tempdata.close).iloc[i], (tempdata.rsi_9).iloc[i], (tempdata.status).iloc[i]) 

        if (tempdata.status).iloc[i] == 0 and (tempdata.rsi_9).iloc[i] > 80:

            tempdata.iloc[i:,-1] = 1

            high_rsi_1 = (tempdata.rsi_9).iloc[i]
            tempdata.iloc[i,tempdata.columns.get_loc('high_rsi_1')] = high_rsi_1

            high_price_1 = (tempdata.close).iloc[i]
            tempdata.iloc[i,tempdata.columns.get_loc('high_price_1')] = high_price_1

        elif (tempdata.status).iloc[i] == 1:

            if (tempdata.rsi_9).iloc[i] > high_rsi_1:
                high_rsi_1 = (tempdata.rsi_9).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_rsi_1')] = high_rsi_1
            if (tempdata.close).iloc[i] > high_price_1:
                high_price_1 = (tempdata.close).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_1')] = high_price_1

            if (tempdata.rsi_9).iloc[i] < 80 and (tempdata.rsi_9).iloc[i] < (tempdata.rsi_25).iloc[i]:
                tempdata.iloc[i:,-1] = 2            

        elif (tempdata.status).iloc[i] == 2:

            if (tempdata.rsi_9).iloc[i] < 70:
                tempdata.iloc[i:,-1] = 3

        elif (tempdata.status).iloc[i] == 3:

            if ((tempdata.close).iloc[i] > high_price_1) and ((tempdata.rsi_9).iloc[i] > (tempdata.rsi_25).iloc[i]):
                tempdata.iloc[i:,-1] = 4

                high_rsi_4 = (tempdata.rsi_9).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_rsi_4')] = high_rsi_4

                high_price_4 = (tempdata.close).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_4')] = high_price_4

        elif (tempdata.status).iloc[i] == 4:

            if (tempdata.rsi_9).iloc[i] > high_rsi_4:
                high_rsi_4 = (tempdata.rsi_9).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_rsi_4')] = high_rsi_4

            if (tempdata.close).iloc[i] > high_price_4:
                high_price_4 = (tempdata.close).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_4')] = high_price_4

    #         print( (tempdata.rsi_9).iloc[i], (tempdata.rsi_25).iloc[i], high_rsi_1, high_rsi_4, high_price_1, high_price_4 )     

            if (high_rsi_4 > high_rsi_1) or (high_rsi_4 > 80):

                tempdata.iloc[i:,-1] = 1

                high_rsi_1 = high_rsi_4
                tempdata.iloc[i,tempdata.columns.get_loc('high_rsi_1')] = high_rsi_1

                high_price_1 = high_price_4 if high_price_4 > high_price_1 else high_price_1
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_1')] = high_price_1

                continue

            if (tempdata.rsi_9).iloc[i] < (tempdata.rsi_25).iloc[i]:
                if (high_rsi_1>high_rsi_4) and (high_price_1<high_price_4):
                    tempdata.iloc[i:,-1] = 5

        elif (tempdata.status).iloc[i] == 5:
            tempdata.iloc[i:,-1] = 6
            print(tempdata.index[i], ', set sell_price = ', (tempdata.open).iloc[i])
            sell_price = (tempdata.open).iloc[i]

        elif (tempdata.status).iloc[i] == 6:

            ### take profit

            if ((tempdata.open).iloc[i]/sell_price) < 0.9:
                buy_price = (tempdata.open).iloc[i]
                print(tempdata.index[i], ', point1 set buy_price = ', buy_price, 'profit = ', round(100*(1-((tempdata.open).iloc[i]/sell_price)),2), '%' )
                tempdata.iloc[i:,-1] = 0

            elif ((tempdata.close).iloc[i]/sell_price) < 0.9:
                buy_price = (tempdata.close).iloc[i]
                print(tempdata.index[i], ', point2 set buy_price = ', buy_price, 'profit = ', round(100*(1-((tempdata.close).iloc[i]/sell_price)),2), '%' )
                tempdata.iloc[i:,-1] = 0

            elif (tempdata.open).iloc[i] > (high_price_4+1) :    
                buy_price = (tempdata.open).iloc[i]
                print(tempdata.index[i], ', point3 set buy_price = ', buy_price, 'profit = ', round(100*(1-((tempdata.open).iloc[i]/sell_price)),2), '%' )
                tempdata.iloc[i:,-1] = 4    
                high_price_1 = high_price_4
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_1')] = high_price_1
                high_price_4 =(tempdata.open).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_4')] = high_price_4

            elif (tempdata.close).iloc[i] > (high_price_4+1) :    
                buy_price = (tempdata.close).iloc[i]
                print(tempdata.index[i], ', point4 set buy_price = ', buy_price, 'profit = ', round(100*(1-((tempdata.close).iloc[i]/sell_price)),2), '%' )
                tempdata.iloc[i:,-1] = 4        
                high_price_1 = high_price_4
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_1')] = high_price_1
                high_price_4 = (tempdata.close).iloc[i]
                tempdata.iloc[i,tempdata.columns.get_loc('high_price_4')] = high_price_4

            ### stop loss

        else :
            continue
    #         print('Error')

    #     print(i, ',' , tempdata.at[i,'close'], tempdata.at[i,'rsi_9'], tempdata.at[i,'status']) 


    print(tempdata)

In [ ]:
# for close in tempdata.items():
#         print("日期:",date," 買進：", close)
        
# for index, row in tempdata.iterrows():
#     print(row['Index'])  
import dateutil

high_rsi_1, high_rsi_4, high_price_1, high_price_4 = (0,)*4

for i in tempdata.index:
    
    if tempdata.at[i,'status'] == 0 and tempdata.at[i,'rsi_9']>80:
        
        tempdata.at[i,'status'] = 1
        high_rsi_1 = tempdata.at[i,'rsi_9']
        high_price_1 = tempdata.at[i,'close']
        
    elif tempdata.at[i,'status'] == 1:
        
        if tempdata.at[i,'rsi_9'] > high_rsi_1:
            high_rsi_1 = tempdata.at[i,'rsi_9']
        if tempdata.at[i,'close'] > high_price_1:
            high_price_1 = tempdata.at[i,'close']
            
        if tempdata.at[i,'rsi_9'] < 80 and tempdata.at[i,'rsi_9'] < tempdata.at[i,'rsi_25']:
            tempdata.at[i+1,'status'] = 2            
        
    elif tempdata.at[i,'status'] == 2:
        
        if tempdata.at[i,'rsi_9'] < 65:
            tempdata.at[i,'status'] = 3 
        
    elif tempdata.at[i,'status'] == 3:
        
        if (tempdata.at[i,'close'] > high_price_1) and (tempdata.at[i,'rsi_9'] > tempdata.at[i,'rsi_25']):
            tempdata.at[i,'status'] = 4
            high_rsi_4 = tempdata.at[i,'rsi_9']
            high_price_4 = tempdata.at[i,'close']
        
    elif tempdata.at[i,'status'] == 4:
        if tempdata.at[i,'rsi_9'] > high_rsi_4:
            high_rsi_4 = tempdata.at[i,'rsi_9']
        if tempdata.at[i,'close'] > high_price_4:
            high_price_4 = tempdata.at[i,'close']
            
        if tempdata.at[i,'rsi_9'] < tempdata.at[i,'rsi_25']:
            if (high_rsi_1>high_rsi_4) and (high_price_1<high_price_4):
                tempdata.at[i,'status'] = 5
            
        
    elif tempdata.at[i,'status'] == 5:
        tempdata.at[i,'status'] == 5
        
    else :
        print('Error')
#         assert(0)
    
    print(i, ',' , tempdata.at[i,'close'], tempdata.at[i,'rsi_9'], tempdata.at[i,'status']) 
    
    
print(tempdata)    
    
# for row in tempdata.itertuples():
#     if(row.rsi_9>80):
#         row.status = 1
        
#     print(row.Index, row.close, row.status)    
# for row in tempdata.iterrows():
#     print(row['close']

In [ ]:
dataset[dataset['stock_id'].isin(['2413'])]

In [ ]:
from finlab.data import Data
import datetime
import talib
import pandas as pd

#抓取股票代號
stockID='0050'

# 可以從 data 中讀取資料
data = Data()

period = 600

# 從 close, high, low 取從最新的一筆資料往前算，2000筆資料
close = data.get('收盤價', period)
high = data.get('最高價', period)
low = data.get('最低價', period)

print("抓取資料完成！")

In [ ]:
base = data.get('股本合計')/10
print(base['2330'])

In [ ]:
# 利用 talib 來計算這檔股票的指標
kd = talib.STOCH(high[stockID].ffill().values, 
                 low[stockID].ffill().values, 
                 close[stockID].ffill().values,
                 fastk_period=9, slowk_period=3
                 , slowd_period=3, slowk_matype=1, slowd_matype=1)

# 將 kd 值 分別轉換成 k、d 兩條 series
k = pd.Series(kd[0], index=close[stockID].index)
d = pd.Series(kd[1], index=close[stockID].index)

#買進訊號為KD黃金交叉，且K小於30
buy = (k > d) & (k.shift(1) < d.shift(1)) & (k < 30)
#賣出訊號為KD死亡交叉，且K大於70
sell = (k < d) & (k.shift(1) > d.shift(1)) & (k > 70)

#secondary_y代表拉長畫線到y軸，讓線更明顯
buy.astype(int).plot(secondary_y=True, color='red')
sell.astype(int).plot(secondary_y=True, color='green')
#畫出股價
close[stockID].plot()

#持有訊號
hold = pd.Series([0]*len(buy), index=buy.index)
hold[buy]=1
hold[sell]=-1
hold.plot()

In [ ]:
hold.plot()

In [ ]:
# hold.plot(figsize = (12,12))
buy.astype(int).plot(secondary_y=True, color='red')
sell.astype(int).plot(secondary_y=True, color='green')
close[stockID].plot(figsize = (12,12))

In [ ]:
#回測
#取出買入/賣出時的價格
buyPrice = close[stockID] * hold
#中括號選擇價格不等於０，也就是買入賣出訊號
buyPrice = buyPrice[buyPrice!=0]
#print(buyPrice)

status = 0 #1:代表持有股票 0:代表沒有股票
bPirce = 0 #買入價格
profit=[0] #損益
profitDate=[0]
tradeTime = 0
for date,price in buyPrice.items():
    #買進訊號
    if(price > 0 and status==0):
        print("日期:",date," 買進：", price)
        status=1
        bPirce=price
    #賣出訊號
    if(price < 0 and status==1):
        print(tradeTime," 日期:",date, " 賣出：", price)
        tradeTime+=1
        status=0
        p = ((-1*price)-bPirce) #損益價差
        profit.append(profit[-1]+p) #算出損益
        profitDate.append(date)

print("總共交易次數：",tradeTime)
print("總損益(價格)：", profit)
#畫出投資獲利
pd.Series(profit).plot()

In [ ]:
# 利用 talib 來計算這檔股票的指標
kd = talib.STOCH(high[stockID].ffill().values, 
                 low[stockID].ffill().values, 
                 close[stockID].ffill().values,
                 fastk_period=9, slowk_period=3
                 , slowd_period=3, slowk_matype=1, slowd_matype=1)

# 將 kd 值 分別轉換成 k、d 兩條 series
k = pd.Series(kd[0], index=close[stockID].index)
d = pd.Series(kd[1], index=close[stockID].index)
RSI = talib.RSI(close[stockID],5)
SMA = talib.SMA(close[stockID],5)
VOL = pd.Series(volume[stockID].ffill().values,index=volume[stockID].index)

print(k)
print(d)
print("----------rsi----------")
print(RSI)
print("----------5ma----------")
print(SMA)
print("----------volume----------")
print(VOL)

#買進訊號為KD黃金交叉，且K小於30
buy = (k > d) & (k.shift(1) < d.shift(1)) & (k < 30)
#賣出訊號為KD死亡交叉，且K大於70
sell = (k < d) & (k.shift(1) > d.shift(1)) & (k > 70)

print(buy)
print(sell)
test = buy | sell
print(test)


#secondary_y代表拉長畫線到y軸，讓線更明顯
buy.astype(int).plot(secondary_y=True, color='red')
sell.astype(int).plot(secondary_y=True, color='green')
#畫出股價
close[stockID].plot()

#持有訊號
hold = pd.Series([0]*len(buy), index=buy.index)
hold[buy]=1
hold[sell]=-1
print(hold)
hold.plot()

In [ ]:
#回測
#取出買入/賣出時的價格
buyPrice = close[stockID] * hold
#中括號選擇價格不等於０，也就是買入賣出訊號
buyPrice = buyPrice[buyPrice!=0]
print(buyPrice)

status = 0 #1:代表持有股票 0:代表沒有股票
bPirce = 0 #買入價格
profit=[0] #損益
profitDate=[0]
tradeTime = 0
for date,price in buyPrice.items():
    #買進訊號
    if(price > 0 and status==0):
        print("日期:",date," 買進：", price)
        status=1
        bPirce=price
    #賣出訊號
    if(price < 0 and status==1):
        print(tradeTime," 日期:",date, " 賣出：", price)
        tradeTime+=1
        status=0
        p = ((-1*price)-bPirce) #損益價差
        profit.append(profit[-1]+p) #算出損益
        profitDate.append(date)

print("總共交易次數：",tradeTime)
print("總損益(價格)：", profit)
#畫出投資獲利
pd.Series(profit).plot()